#+TITLE: Chapter02_el
* Κεφάλαιο 2 - Πρώτα Βήματα

** Προοίμιο

/γενικά χαρακτηριστικά των δύο περιβαλλόντων με έμφαση στα δομικά στοιχεία και τους τρόπους που αυτά αλληλεπιδρούν/
/αρχιτεκτονική, αρχές λειτουργίας, λεξιλόγιο/
/Άσκηση: "Count Me In"/

/θέματα Pd: bang, toggle, arithmetic operators, number boxes, properties, float, metro/

** Κύριο Μέρος

*** Pure Data

Η γλώσσα του Pd μπορεί να διακριθεί σε εργαλεία που αφορούν τη διαχείριση αριθμητικών δεδομένων και εργαλεία που αφορούν τη διαχείριση σήματος.
Στο παρόν κεφάλαιο θα εστιάσουμε στην πρώτη κατηγορία.

Βασική θέση στο λεξιλόγιο της γλώσσας καταλαμβάνει το εργαλείο bang.(shift-cmd-B)
Ουσιαστικά αποτελεί ένα εικονικό κόμβιο, εν δυνάμει φορέα μιας ενέργειας.
Πατώντας το κόμβιο η ενέργεια αυτή μεταδίδεται από την έξοδο στα συνδεδεμένα αντικείμενα.
Επιπλέον της χειροκίνητης ενεργοποίησης, το κόμβιο ενεργοποιείται και άνωθεν από τα συνδεδεμένα αντικείμενα.
Συνεπώς, το bang έχει μια είσοδο και μια έξοδο. *Figure "Bang"*

Άλλο βασικό αντικείμενο είναι το number (cmd-3), το οποίο απεικονίζει και μεταδίδει αριθμητικά δεδομένα.
Μπορεί να ενεργοποιηθεί χειροκίνητα, πληκτρολογώντας μια τιμή στο πεδίο και πατώντας το enter,
ή κλικάροντας και σέρνοντας πατημένα προς πάνω ή κάτω για αύξηση και μείωση τιμών αντίστοιχα.
Χρήσιμο στη χειροκίνητη λειτουργία είναι να θέσουμε ελάχιστο και μέγιστο όριο στις αποτυπώμενες τιμές,
και με αυτή την αφορμή να δούμε πώς μπορούμε γενικά να επέμβουμε στις ιδιότητες των αντικειμένων.

Με δεξί κλικ στο number εμφανίζεται η επιλογή properties. *Figure "Properties"*
Εδώ μπορούμε να τροποποιήσουμε τις τιμές και καταστάσεις διάφορων εσωτερικών παραμέτρων.
Σε αυτή την περίπτωση ορίζουμε ελάχιστη και μέγιστη τιμή του number στην κατηγορία Limits και τα πεδία Lower και Upper.
Να σημειωθεί εδώ πως κάποια αντικείμενα δεν δίνουν την επιλογή τροποποίησης των ιδιοτήτων τους.

Το αντικείμενο number δέχεται τιμές και από άλλα αντικείμενα, το καθένα από τα οποία επενεργεί με συγκεκριμένο τρόπο.
Ας δούμε το πρόγραμμα στην Εικόνα *Figure "Number"*
Δύο messages και ένα bang είναι συνδεδεμένα σε ένα number, και αυτό με τη σειρά του συνδέεται σε ένα print.
Με το bang στέλνουμε την τρέχουσα τιμή του number στο print.
Πατάμε το message με τον αριθμό "7" και παρατηρούμε πως εμφανίζεται στο number και στην κονσόλα μας.
Αντίθετα, πατώντας τo message "set 9" παρατηρούμε πως ο αριθμός "9" εμφανίζεται μόνο στο number.
Αυτό συμβαίνει, επειδή το πρόθεμα "set" σε ένα message έχει την ιδιότητα να διαμοιράζει την πληροφορία μόνο στο επόμενο στάδιο,
χωρίς να την πυροδοτεί περαιτέρω, κι έτσι αυτή δεν φτάνει στο print.

Οι αριθμητικοί τελεστές είναι αντικείμενα, με τα οποία πραγματοποιούμε αριθμητικές πράξεις,
συγκεκριμένα πρόσθεση, αφαίρεση, πολλαπλασιασμό, διαίρεση, και ύψωση σε δύναμη. *Figure "Math"*
Παρατηρούμε πως τα αντικείμενα αυτά έχουν δύο εισόδους.
Κάθε είσοδος πλην της αριστερής ονομάζεται "κρύα" και έχει τη λειτουργία να αποθηκεύει την εισαγόμενη πληροφορία,
χωρίς όμως να πυροδοτεί την έξοδο του αντικειμένου.
Η αριστερή είσοδος ονομάζεται "ζεστή" και, δεχόμενη πληροφορία, εκτελεί την πράξη και πυροδοτεί την έξοδο.
Οι αριθμητικοί τελεστές έχουν αρχική τιμή μηδέν.
Κάθε τιμή που θα εισαχθεί στην κρύα είσοδο, θα αποθηκευτεί στη θέση της αρχικής, χωρίς να εξάγει αποτέλεσμα.
Η τιμή που εισαχθεί στη ζεστή είσοδο, θα πραγματοποιήσει την πράξη και θα εξάγει αποτέλεσμα.

Να σημειωθεί εδώ πως μπορούμε να ορίσουμε παραμέτρους των αντικειμένων με μια αρχική τιμή δίπλα στην ονομασία τους.
Στην εικόνα *Figure "MathAct"* βλέπουμε ένα αντικείμενο διαίρεσης με αρχική αναγραφόμενη τιμή "3".
Κάθε τιμή που εισάγεται στη ζεστή είσοδο θα διαιρεθεί με αυτή την αρχική τιμή, εκτός αν έχει αντικατασταθεί από άλλη στην κρύα είσοδο.

Για την Άσκηση του Κεφαλαίου θα υλοποιήσουμε έναν μετρητή ενεργειών (bangs).
Το συγκεκριμένο εργαλείο είναι σημαντικό για τον αλγοριθμικό συσχετισμό μουσικών γεγονότων, αυτοματοποιημένες διαδικασίες,
εισαγωγή δεδομένων από τον χρήστη, και άλλες χρήσεις.

Για την υλοποίηση της Άσκησης θα χρειαστούμε τα εξής 3 αντικείμενα: toggle, metro, και float.

Το αντικείμενο metro παράγει bangs με συγκεκριμένη περιοδικότητα, την οποία ορίζουμε στην κρύα είσοδο ως χιλιοστά του δευτερολέπτου (mlsecs).
Οποιαδήποτε μη-μηδενική τιμή στη ζεστή είσοδο ξεκινάει τη διαδικασία, ενώ η μηδενική τιμή τη σταματάει.
Ως διακόπτη του metro θα χρησιμοποιήσουμε το αντικείμενο toggle, το οποίο ενεργοποιημένο εξάγει την τιμή 1 και απενεργοποιημένο την τιμή 0.
Το αντικείμενο float αποθηκεύει μια ακέραια ή δεκαδική τιμή στην κρύα είσοδο, την οποία εξάγει, όταν ενεργοποιείται η ζεστή είσοδος.
Για τον μετρητή μας ουσιαστικά χρειάζεται να πυροδοτούμε την αποθηκευμένη τιμή του float, να προσθέτουμε σε αυτήν την τιμή 1,
και να αποθηκεύουμε τη νέα αυτή τιμή για την επόμενη πυροδότηση.

Συνδέουμε στο πρόγραμμα το αντικείμενο toggle στη ζεστή είσοδο ενός metro mε αρχική τιμή 1000(mlsecs).
Έπειτα, συνδέουμε την έξοδο του bang στη ζεστή είσοδο του float, διαμεσολαβώντας ένα bang, για να παρακολουθούμε τη διαδικασία.
Δίνουμε στο float αρχική τιμή 0 και συνδέουμε την έξοδο με τη ζεστή είσοδο αντικειμένου πρόσθεσης με αρχική τιμή 1.
Το αποτέλεσμα της πρόσθεσης αποτυπώνεται σε ένα αντικείμενο number, αλλά και αποθηκεύεται στην κρύα είσοδο του αριθμητικού τελεστή.
Με τον διακόπτη toggle μπορούμε να εκκινούμε και να παύουμε την καταμέτρηση από την τρέχουσα τιμή,
ενώ για επανεκκίνηση της διαδικασίας από την αρχή χρειάζεται να τροφοδοτήσουμε στο toggle και στην κρύα είσοδο του float την τιμή 0. *Figure "Counter"*



*** SuperCollider
