#+TITLE: Chapter06_el
* Κεφάλαιο 6 - Το Ηχητικό Δείγμα

** Προοίμιο
/εισαγωγή και επεξεργασία ηχητικού δείγματος./
/ιστορική εξέλιξη της δειγματοληψίας (sampling)/
/εργαλεία εισαγωγής, αναπαραγωγής, και τεμαχισμού δείγματος, και ανακατανομής τμημάτων./
/τεχνικές επεξεργασίας πλάτους σήματος (κανονικοποίηση (normalization), συμπίεση (compression) διόγκωση (expansion)./

/θέματα Pd: readsf~, openpanel, writesf~, spigot, soundfiler, tabplay~ tabread4~, tabwrite~, adc~, table/

** Κύριο Μέρος

Η αναπαραγωγή ηχητικών δειγμάτων στο Pure Data γίνεται με διάφορους τρόπους.
Για απλή αναπαραγωγή αρχείων αποθηκευμένων στον υπολογιστή ενδείκνυται το αντικείμενο readsf~.
Στέλνουμε στο readsf~ διαδοχικά: ένα μήνυμα με την εντολή open και το πλήρες όνομα του αρχείου προς ανάγνωση, και ένα μήνυμα με την εντολή start,
Μήνυμα με την εντολή stop σταματάει την αναπαραγωγή. *Figure "ReadFile"*
Σε κάθε περίπτωση, το αρχείο πρέπει να βρίσκεται στο ίδιο directory με το πρόγραμμα μας.
Για να κατευθύνουμε το readsf~ σε αρχείο από διαφορετικό directory, ενεργοποιούμε με bang την είσοδο του αντικειμένου openpanel,
ώστε να ανοίξει ένα παράθυρο αναζήτησης, να επιλέξουμε το αρχείο, και να το αναθέσουμε σε μεταβλητή της εντολής open. *Figure "OpenFile"*

Για αρχεία με περισσότερα από ένα κανάλια θέτουμε ως όρισμα του readsf~ το επιθυμητό πλήθος καναλιών.
Στο *Figure "SampleLoop"* εισάγουμε προς αναπαραγωγή ένα στερεοφωνικό αρχείο.
Το readsf~ έχει τώρα 2 εξόδους σήματος, για αριστερό και δεξί κανάλι αντίστοιχα.
Για τη δημιουργία βρόχου επανάληψης του αρχείου (loop) αξιοποιούμε την τελευταία, δεξιά έξοδο του readsf~ σε συνδυασμό με το αντικείμενο spigot.
Η τελευταία έξοδος του readsf~, αλλά και των υπόλοιπων αντικειμένων αναπαραγωγής αρχείων, εξάγει ένα bang με την ολοκλήρωση της αναπαραγωγής.
To spigot αποτελεί ουσιαστικά μια πύλη της πληροφορίας από τη ζεστή είσοδο προς την έξοδο της.
Η πύλη ανοίγει και κλείνει μέσω toggle στην κρύα είσοδο.
Με αυτόν τον τρόπο ελέγχουμε την επανατροφοδότηση του bang ολοκλήρωσης στο bang αναπαραγωγής.

Εναλλακτικός τρόπος αναπαραγωγής ηχητικών αρχείων είναι μέσω array.
Όπως έχουμε δει, το array αποτελεί πίνακα αποθήκευσης τιμών.
Αν αυτές οι τιμές αντιστοιχούν στο πλάτος ενός σήματος ανά δείγμα, μπορούμε μετά να τις διαβάσουμε για αναπαραγωγή του σήματος.
Στέλνουμε στο αντικείμενο soundfiler μήνυμα με τις εντολές read και resize, ώστε το μέγεθος του πίνακα να προσαρμοστεί αυτόματα στο πλήθος δειγμάτων του αρχείου,
και το όνομα του array που θα αποθηκεύσουμε το αρχείο μας. *Figure "Soundfiler"*
Με το αντικείμενο tabplay~ μπορούμε στέλνοντας bang να παίξουμε ολόκληρο το αρχείο, στέλνοντας δε μήνυμα με ένα σημείο έναρξης και μια διάρκεια σε δείγματα
μπορούμε να παίξουμε μεμονωμένα τμήματα. Στο παράδειγμα, το μήνυμα 44100 88200 θα ξεκινήσει την αναπαραγωγή στο 1ο δευτερόλεπτο για 2 ακόμη δευτερόλεπτα (2x44100).

Περισσότερη ευελιξία μας δίνει το αντικείμενο tabread4~.
Στο *Figure "StereoBuffer"* έχουμε εισάγει σε 2 arrays τα κανάλια ενός στερεοφωνικού αρχείου, και εξάγουμε από την αριστερή έξοδο του soundfiler το μέγεθος του αρχείου σε δείγματα.
Για την αναπαραγωγή χρειαζόμαστε ένα tabread4~ για κάθε κανάλι.
Αυτή τη φορά οδηγούμε τη σάρωση των δειγμάτων με ένα phasor~, του οποίου οι τιμές από 0 έως 1 πολλαπλασιάζονται με το πλήθος δειμάτων του αρχείου. *Figure "PlaybackSpeed"*
H χρήση του phasor~ δημιουργεί αυτόματα βρόχο επανάληψης.
Απευθείας εισαγωγή τιμών στη ζεστή είσοδο του phasor~ επηρεάζει τη συχνότητα του επιβραδύνοντας ή επιταχύνοντας ανάλογα την αναπαραγωγή του αρχείου.
Ας δούμε τώρα το μέρος του προγράμματος πάνω από το σχόλιο.
Διαιρώντας τα δείγματα που αντιστοιχούν σε 1 δευτερόλεπτο (44100) με το πλήθος δειγμάτων του σήματος παίρνουμε τη συχνότητα του phasor~ για αναπαραγωγή του αρχείου σε κανονικό χρόνο.
Παρεμβάλλοντας ένα αντικείμενο πολλαπλασιασμού μπορούμε να ελέγχουμε με ένα hslider την ταχύτητα, αλλά και τη διεύθυνση, αναπαραγωγής.

Τελευταίο θέμα του κεφαλαίου αποτελεί η καταγραφή στον υπολογιστή της εξόδου αντικειμένων επεξεργασίας σήματος με το αντικείμενο writesf~.
Αρχικά, δημιουργούμε με την εντολή open τον χώρο αποθήκευσης και το επιθυμητό όνομα για το νέο αρχείο.
Οι εντολές start και stop ενεργοποιούν και τερματίζουν αντίστοιχα τη ροή ηχητικών δεδομένων προς ηχογράφηση. *Figure "WriteFile"*
Αν θέλουμε να καταγράψουμε την είσοδο στην κάρτα ήχου του υπολογιστή, όπως το μικρόφωνο, χρησιμοποιούμε το αντικείμενο adc~.
Στο *Figure "Record"* ηχογραφούμε το adc~ σε ένα table, ουσιαστικά ένα array χωρίς τη γραφική απεικόνιση.
Το table δέχεται ως ορίσματα ένα όνομα και ένα μέγεθος. Με bang στο αντικείμενο tabwrite~ ξεκινάει η καταγραφή μέχρι να γεμίσει ο πίνακας.
Αντίστοιχα, με bang στο tabplay~ αναπαράγεται η καταγεγραμμένη πληροφορία.
