#+TITLE: Chapter05_el
* Κεφάλαιο 5 - Μουσική Δόμηση του Ήχου

** Προοίμιο
/Στο έβδομο κεφάλαιο αναλύεται η διαχείριση midi πληροφοριών, από τη μετατροπή του μεγέθους της συχνότητας σε midi τιμή,/
/μέχρι τη δημιουργία και στις δύο γλώσσες προγραμματισμού μιας γεννήτριας ηχητικών συμβάντων/
/με δυνατότητες ενεργοποίησης των midi ήχων του υπολογιστή και οργάνωσής τους σε ακολουθίες/
/κατά τα πρότυπα διαφορετικών μουσικών κλιμάκων./
/Επεξηγούνται οι προγραμματιστικές έννοιες των μοτίβων (patterns), επαναλαμβανόμενων διεργασιών (routines and tasks),/
/και των πληροφοριακών ροών (streams), ως προς τη λειτουργία τους για τη διαχείριση ηχητικών δεδομένων./
/Επιπλέον, περιγράφονται οι έννοιες της οκτάβας και της μουσικής κλίμακας,/
/και αναφέρεται η γέννηση και ο σημαντικός αντίκτυπος της midi τεχνολογίας στη μουσική βιομηχανία./
/Τέλος, συνδυάζονται προηγούμενες γνώσεις σχετικές με τα μοντέλα πιθανοκρατικής διαχείρισης της πληροφορίας/
/για τη δημιουργία εργαλείου για μουσικό αυτοσχεδιασμό υποβοηθούμενο από τον υπολογιστή./
/Αναφέρονται οι ηχητικές ιδιότητες της θεμελιώδους συχνότητας και των αρμονικών,/
/Άσκηση: "Up and Down the Ladder"/

/θέματα Pd: midi settings, notein, noteout, makenote, mtof, hslider, i, mod, sel, vradio, unpack/

** Κύριο Μέρος

*** Pure Data

Το πρωτόκολλο MIDI επιτρέπει στο Pure Data να επικοινωνεί με άλλα υλισμικά και λογισμικά, τόσο στην είσοδο όσο και στην έξοδο της πληροφορίας.
Για παράδειγμα, μπορούμε να εισάγουμε από έναν ελεγκτή με πλήκτρα και ολισθητήρες δεδομένα στο πρόγραμμα μας,
ή να τροφοδοτούμε με τιμές υπολογισμένες στο Pure Data έναν εξωτερικό συνθετητή.
Οι συνδεδεμένες MIDI συσκευές ορίζονται από το Μενού Εντολών > Media > ΜIDI Settings, στα πεδία συσκευών Εισόδου και Εξόδου αντίστοιχα.
Στο *Figure "Midi Settings"* έχουμε συνδέσει στην MIDI είσοδο του Pure Data το κλαβιέ M-Audio Keystation Mini 32,
ενώ η MIDI έξοδος δρομολογείται στην είσοδο του εικονικού συνθετητή Simple Synth. *Figure "MidiInOut"*

Η βασική δομή MIDI δεδομένων είναι ένα ζεύγος τιμών, όπου η πρώτη τιμή αντιστοιχεί στη νότα και η δεύτερη στην ένταση αναπαραγωγής της.
Την αντιστοιχία των MIDI τιμών με νότες ανά οκτάβα βλέπουμε στο *Figure "MidiNotes"*.
Η ένταση εκτείνεται στην κλίμακα τιμών από 0 έως 127 (μέγιστη ένταση).
Ένα ζεύγος τιμών με μη-μηδενική τιμή έντασης (note-on) ενεργοποιεί την αντίστοιχη νότα,
ενώ για την παύση της χρειάζεται να σταλεί η ίδια τιμή νότας με μηδενική τιμή έντασης (note-off).

Το αντικείμενο notein εξετάζει τις εισερχόμενες MIDI πληροφορίες και εξάγει στις εξόδους του τις τιμές νότας, έντασης, και καναλιού.
Αντίστοιχα, το αντικείμενο noteout δέχεται στις εισόδους του τις τιμές νότας, έντασης, και καναλιού, για αποστολή σε συνδεδεμένες MIDI συσκευές.
Και στα δύο αντικείμενα μπορούμε να θέσουμε ως αρχική τιμή το συγκεκριμένο MIDI κανάλι που θέλουμε να "ακούνε".
Στο *Figure "NoteInOut"* βλέπουμε εναλλακτικούς τρόπους δημιουργίας μιας νότας στο MIDI κανάλι 1,
είτε με απευθείας σύνδεση μηνυμάτων note-on και note-off στη ζεστή είσοδο του noteout (αριστερά),
είτε με μεσολάβηση του αντικειμένου unpack για περισσότερο έλεγχο (κέντρο),
είτε με σύνδεση των εξόδων του notein με τις αντίστοιχες εισόδους του noteout, για να φτάνει η πληροφορία από τα πλήκτρα του κλαβιέ μας στον εικονικό συνθετητή.

Το αντικείμενο makenote μπορεί να προγραμματίζει την αυτόματη αποστολή note-off μετά από ορισμένο χρονικό διάστημα.
Συνεπώς δέχεται τρεις τιμές στις αντίστοιχες εισόδους ή ως αρχικές τιμές: για τη νότα, την ένταση, και τη διάρκεια της. *Figure "MakeNote"*

Υπάρχουν πολλά ακόμη αντικείμενα για διαχείριση MIDI πληροφορίας, όπως ctlin και ctlout για συνεχείς τιμές ελεγκτών,
pgmin και pgmout για αλλαγή MIDI προγράμματος (που συνήθως αντιστοιχεί στον επιλεγμένο ήχο από τους διαθέσιμους του MIDI οργάνου),
bendin και bendout για pitchbend δεδομένα, κ.α.

Για να οδηγήσουμε με MIDI νότες τον ταλαντωτή μας θα συνδέσουμε στη ζεστή είσοδο του osc~ το αντικείμενο mtof,
το οποίο μετατρέπει αριθμητικές τιμές midi σε συχνότητα.
Μέ έναν οριζόντιο ολισθητή (hslider) μπορούμε να στέλνουμε τέτοιες τιμές σε συγκεκριμένο εύρος που ορίζουμε από τις ιδιότητες του αντικειμένου.
Για παράδειγμα, οι τιμές από 60 έως 72 αντιστοιχούν στις συχνότητες των νοοτών από C4 έως C5.
Αν θέλουμε να αποφύγουμε γλύστρημα (glissando) στο ακουστό αποτέλεσμα λόγω μεταβολής των δεκαδικών τιμών του ολισθητή,
παρεμβάλουμε το αντικείμενο i (integer), το οποίο κβαντίζει (κανονικοποιεί?) έναν δεκαδικό αριθμό στον κοντινότερο προς το 0 ακέραιο.
Έτσι, επιτυγχάνουμε διακριτά βήματα από νότα σε νότα. *Figure "MidiToFreq"*

Η άσκηση του Κεφαλαίου αφορά στη δημιουργία MIDI νοτών σε τονικές ακολουθίες ματζόρε και μινόρε τρόπου. *Figure "MidiScales"*
Το πρόγραμμα μας στέλνει τα αποτελέσματα του σε μια έξοδο (outlet midiNotes), ώστε να μπορεί να αξιοποιηθεί ως υπο-πρόγραμμα,
σε συνδυασμό ενδεικτικά με κάποια γεννήτρια ταλαντωτών ή κάποιο συνθετητή. *Figure "MidiScalesSub"*
Αποτελείται από 3 βασικά μέρη:
τη δημιουργία επαναλαμβανόμενων ακολουθιών 8 τιμών με αύξηση 1 ανά βήμα (υπο-πρόγραμμα "pd counter"),
τον έλεγχο αυτών των τιμών για την ενεργοποίηση των αντίστοιχων MIDI νoτών (βασικό πρόγραμμα), και
τον ορισμό των MIDI νοτών ανάλογα με τον επιθυμητό ματζόρε ή μινόρε τρόπο (υπο-πρόγραμμα "pd noteParser".

Για τη δημιουργία των 8 τιμών χρειάζεται να προσθέσουμε στον μετρητή μας το αντικείμενο mod ή αλλιώς %. *Figure "CounterPlusMod"*
Το αντικείμενο αυτό διαιρεί την τιμή της ζεστής εισόδου με την τιμή της κρύας και εξάγει το υπόλοιπο.
Έτσι, τροποποιούμε μια συνεχώς αυξανόμενη ακολουθία σε επαναλαμβανόμενη ορισμένου εύρους.

Για τον έλεγχο των τιμών χρησιμοποιούμε το αντικείμενο select ή αλλιώς sel.
Αυτό συγκρίνει τις τιμές εισόδου με τα ορίσματα του και, αν συμφωνούν, εξάγει bang από την αντίστοιχη έξοδο,
αλλιώς τις αφήνει να διαπεράσουν από την τελευταία έξοδο.
Με τον τρόπο αυτό, κάθε βήμα του μετρητή κατευθύνεται και στην αντίστοιχη MIDI νότα.

Για τον ορισμό των MIDI νοτών ανάλογα με τον επιθυμητό τρόπο, αρχικά χρησιμοποιούμε το αντικείμενο vradio,
το οποίο για κάθε διαφορετικό κελί που επιλέγουμε, εξάγει την αντίστοιχη τιμή: 0 για το πρώτο, 1 για το δεύτερο κ.ο.κ.
Το πλήθος των κελιών το ορίζουμε από τις ιδιότητες του αντικειμένου.
Συνδυάζοντας το vradio με ένα select μέσα στο υπο-προγραμμα "pd noteParser" επιλέγεται  η αντίστοιχη ακολουθία MIDI νοτών. *Figure "NoteParser"*
To αντικείμενο unpack δρομολογεί το κάθε στοιχείο της λίστας στην αντίστοιχη έξοδο,
και το αντικείμενο set με μία μεταβλητή μεταφέρει την τιμή ένα στάδιο παρακάτω χωρίς περαιτέρω πυροδότηση.


*** SuperCollider
