#+TITLE: Chapter 1_el


* Κεφάλαιο 1 - Εισαγωγή στα Περιβάλλοντα Μουσικού Προγραμματισμού

** Προοίμιο

/ιστορική αναδρομή στη δημιουργία και εξέλιξη των γλωσσών μουσικού προγραμματισμού με έμφαση σε Pd και SC/
/κοινωνικοί, πολιτικοί, και τεχνολογικοί παράγοντες που έπαιξαν καθοριστικό ρόλο στην ανάπτυξη και διάδοση των εν λόγω εργαλείων/
/πρώτες απόπειρες μουσικής σύνθεσης μέσω υπολογιστή μέχρι τον σύγχρονο εκδημοκρατισμό των τεχνολογικών μέσων για ηχητική σύνθεση και επεξεργασία/
/Άσκηση: "Hello Music"/

/Θέματα Pd: ??comment??, εγκατάσταση, παρουσίαση περιβάλλοντος, objects, messages, κοινότητα, βοήθεια/

** Κύριο Μέρος

*** Pure Data
Τρέχοντας το πρόγραμμα μετά την εγκατάσταση, το μοναδικό παράθυρο που βλέπουμε είναι η κονσόλα (terminal). *Figure "Terminal"* Η κονσόλα χρησιμεύει για τη γνωστοποίηση στον χρήστη τυχόν σφαλμάτων και την παρακολούθηση στοχευμένων δεδομένων του κώδικα. Στην κονσόλα βρίσκεται επίσης το πεδίο ενεργοποίησης του ήχου. *Figure "InOut"* Για να συντελεστεί όμως η παραγωγή οποιουδήποτε ηχητικού αποτελέσματος, θα πρέπει το Pure Date να είναι συνδεδεμένο με την κάρτα ήχου του υπολογιστή.

Επιλέγοντας π.χ. αριστερά τα πεδία /80/ και /tone/ θα πρέπει να ακούμε έναν τόνο 80Hz.

Σύμφωνα με τη συνήθη πρακτική των σύγχρονων προγραμμάτων, το Pure Data διαθέτει γραμμή μενού εντολών (menu bar) στην κορυφή της οθόνης. *Figure "MenuBar"* Από εκεί μπορεί ο χρήστης να καλέσει τις βασικότερες εντολές του προγράμματος, αλλά και να δει για την κάθε μια την αντίστοιχη συντόμευση. Στο παρόν σύγγραμμα προτείνεται ο τρόπος των συντομεύσεων, οι οποίες θα αναγράφονται σε παρενθέσεις. Εντούτοις, ο αναγνώστης μπορεί να ακολουθήσει όποιον τρόπο κρίνει πιο βολικό. Να σημειωθεί, επίσης, πως τα παραδείγματα υλοποίησης έχουν πραγματοποιηθεί σε περιβάλλον macOS. Σε περιβάλλον Windows η αντιστοιχία του βασικού κουμπιού συντομεύσεων command (cmd) είναι το control (ctrl).
=======
Τρέχοντας το πρόγραμμα μετά την εγκατάσταση, το μοναδικό παράθυρο που βλέπουμε είναι η κονσόλα (terminal). *Figure "Terminal"*
Η κονσόλα χρησιμεύει για τη γνωστοποίηση στον χρήστη τυχόν σφαλμάτων και την παρακολούθηση στοχευμένων δεδομένων του κώδικα.

Στην κονσόλα βρίσκεται επίσης το πεδίο ενεργοποίησης του ήχου. *Figure "InOut"*
Για να συντελεστεί όμως η παραγωγή οποιουδήποτε ηχητικού αποτελέσματος, θα πρέπει το Pure Date να είναι συνδεδεμένο με την κάρτα ήχου του υπολογιστή.
Η επιλογή των κατάλληλων συσκευών Εισόδου/Εξόδου γίνεται ως εξής: /Γραμμή Εργαλειών >> Media >> Audio Settings >> Input/Output Devices/. *Figure "Settings"*
Δοκιμή πως όλα είναι σωστά συνδεδεμένα μπορούμε να κάνουμε μέσω: /Γραμμή Εργαλειών >> Media >> Test Audio and Midi/. *Figure "TestAudio"*
Επιλέγοντας π.χ. αριστερά τα πεδία /80/ και /tone/ θα πρέπει να ακούμε έναν τόνο 80Hz.
>>>>>>> main

Για να αρχίσουμε να προγραμματίζουμε χρειάζεται να δημιουργήσουμε ένα νέο αρχείο (patch) (cmd-N). Εμφανίζεται σε παράθυρο ένα κενό έγγραφο, το οποίο θα αναφέρεται εφ'εξής ως "πρόγραμμα". *Figure "NewPatch"* Το κενό ως σημείο αφετηρίας δεν πρέπει να μας φοβίζει, καθώς έτσι μπορούμε χωρίς κανένα περιορισμό να δημιουργήσουμε το πρόγραμμα που επιθυμούμε. Φανταστείτε πως έχουμε έναν λευκό καμβά, για να υποδεχτεί τα χρώματα της φαντασίας μας.

Τα προγράμματα στο Pure Data έχουν δύο (2) πιθανές καταστάσεις: Στην κατάσταση Επεξεργασίας (Edit mode) μπορούμε να εισάγουμε και να τροποποιούμε τον κώδικα μας. Στην κατάσταση Λειτουργίας (Run mode) μπορούμε να εκτελούμε τον κώδικα και να τον τροφοδοτούμε με δεδομένα σε πραγματικό χρόνο. Η μετάβαση ανάμεσα στις δύο καταστάσεις γίνεται με (cmd-Ε). Φέρνουμε το κενό -μέχρι στιγμής- πρόγραμμα μας σε κατάσταση επεξεργασίας και παρατηρούμε την ένδειξη *edit* στην κορυφή. *Figure "EditMode"* Είμαστε έτοιμοι να προγραμματίσουμε!

Για την πρώτη μας άσκηση θα παραφράσουμε την -κλασική πια στην εκμάθηση γλωσσών προγραμματισμού- άσκηση εμφάνισης του μηνύματος "Hello World". Αντ'αυτού επιλέγουμε να εμφανίσουμε "Hello Music" και μάλιστα η εντολή αυτή να εκτελείται αυτόματα με το άνοιγμα του προγράμματος. Το πρόγραμμα αυτό, μέχρι το τέλος αυτού του συγγράμματος, θα φιλοξενεί ένα όργανο ηχητικής δημιουργίας.

Για την υλοποίηση της Άσκησης θα χρειαστούμε τα εξής 3 αντικείμενα: message, print, loadbang

Εισάγουμε στο πρόγραμμα μας ένα αντικείμενο message (cmd-2).
Παρατηρούμε πως το αντικείμενο κολλάει στον κέρσορα μας και χρειάζεται να κλικάρουμε σε όποιο σημείο του καμβά θέλουμε να το αποθέσουμε.
Παρατηρούμε επίσης πως σε δύο σημεία, ένα πάνω και ένα κάτω, το περίγραμμα του αντικειμένου είναι πιο έντονο.
Το πάνω σημείο αποτελεί την είσοδο του αντικειμένου, ενώ το κάτω την έξοδο του.
Συνεπώς, το αντικείμενο message έχει μία είσοδο και μία έξοδο, ώστε να επικοινωνεί με άλλα αντικείμενα.
Γράφουμε μέσα στο πλαίσιο του αντικειμένου τη φράση "Hello Music" και κλικάρουμε οπουδήποτε έξω από αυτό στον καμβά.

Το μήνυμα αυτό χρειάζεται ένα αντικείμενο, το οποίο θα φροντίσει για την εμφάνιση του μηνύματος στην κονσόλα.
Εισάγουμε στο πρόγραμμα ένα αντικείμενο print (cmd-1 και έπειτα πληκτρολογούμε στο πεδίο του αντικειμένου "print")
To αντικείμενο print έχει μόνο μία είσοδο, με την οποία πρέπει να ενώσουμε την έξοδο του message.

Η διαδικασία σύνδεσης δύο αντικειμένων συντελείται ως εξής:
Κρατώντας τον κέρσορα πάνω από μια έξοδο, αυτός παίρνει τη μορφή κύκλου.
Κλικάρουμε (δεξί κλικ) και κρατώντας πατημένο το κουμπί του ποντικιού (ή την επιφάνεια του touchpad) σέρνουμε προς την επιθυμητή είσοδο.
Όταν εμφανιστεί πάλι κύκλος, αφήνουμε το κουμπί, για να ολοκληρωθεί η σύνδεση.

Τώρα που συνδέσαμε το message με το print κλειδώνουμε το πρόγραμμα και πατάμε το message. *Figure "FirstConnection"*
Θα δούμε να εμφανίζεται στην κονσόλα μας το επιθυμητό μήνυμα. *Figure "HelloMusic"*
Για να εμφανίζεται το μήνυμα κάθε φορά που ανοίγουμε το πρόγραμμα, χρειαζόμαστε ένα αντικείμενο που να μιμείται το χειροκίνητο πάτημα του message.
Ξεκλειδώνουμε το πρόγραμμα και εισάγουμε το αντικείμενο loadbang, όπως κάναμε πριν με το αντικείμενο print.
Ενώνουμε την έξοδο του loadbang με την είσοδο του message. *Figure "FirstSystem"*
Κλειδώνουμε το πρόγραμμα και το αποθηκεύουμε με την ενδεικτική ονομασία "MyPdSynth" (μενού εντολών >> save as).
Την επόμενη φορά που θα ανοίξουμε το πρόγραμμα, το μήνυμα θα εμφανιστεί αυτόματα στην κονσόλα.


*** SuperCollider
