* Chapter 1

Pure Data (or Pd) is a real-time graphical programming environment for audio, video, and graphical processing.
Written by Miller S. Puckette (previous co-developed the well known and similarly structured software Max/Msp).
Το Pure Data (ή Pd) είναι μια οπτική γλώσσα προγραμματισμού που αναπτύχθηκε από τον Miller Puckette κατά τη δεκαετία του 1990
PureData & MaxMsp θεωρούνται μέλη της οικογένειας γλωσσών Patcher
Το Pure Data και το Max είναι παραδείγματα γλωσσών ροής δεδομένων.
Σε αυτές τις γλώσσες, οι συναρτήσεις ή τα αντικείμενα (objects) συνδέονται μεταξύ τους σε ένα γραφικό περιβάλλον
που μοντελοποιεί την ροή του ελέγχου και του ήχου.

/Το Pd σχεδιάστηκε ώστε να προσφέρει ένα εξαιρετικά μη δομημένο περιβάλλον για την περιγραφή δομών δεδομένων και την γραφική τους εμφάνιση.
Η βασική ιδέα είναι ότι ο χρήστης μπορεί να εμφανίσει κάθε είδος δεδομένων που θέλει, συσχετίζοντάς το με οποιονδήποτε τρόπο με την εμφάνισή του αυτή./


Open Source! As opposed to Max/Msp.

μπορεί να δημιουργήσει και να επεξεργαστεί βίντεο, γραφικά OpenGL, εικόνες και άλλα αντικείμενα πολυμέσων
σε πραγματικό χρόνο με πρακτικά ανεξάντλητες δυνατότητες διαδραστικότητας, ήχου, εξωτερικών αισθητήρων, κλπ.


Σαν λογισμικό ψηφιακής επεξεργασίας σήματος (Digital signal processing, DSP) δέχεται δεδομένα σε δύο ρυθμούς (rates):
δείγματα ήχου (audio rate), με ρυθμό που συμφωνεί με το υλικό, όπως 44100 δείγματα/δευτερόλεπτο,
και σήματα ελέγχου (control rate), με ρυθμό 1 block κάθε 64 δείγματα.
Τα σήματα ελέγχου και ήχου συνήθως ρέουν ανάμεσα στα αντικείμενα μέσω συνδέσεων
από εξόδους (outlets) ενός αντικειμένου σε εισόδους (inlets) κάποιου άλλου αντικειμένου.


Το Pd υποστηρίζει 4 βασικούς τύπους από οντότητες κειμένου:
μηνύματα (messages), αντικείμενα (objects), άτομα (atoms) και σχόλια (comments).
Τα άτομα είναι η βασικότερη μονάδα δεδομένων στο Pd και μπορούν να είναι
ένας αριθμός κινητής υποδιαστολής (float), ένα σύμβολο (symbol) ή έναν δείκτη προς μια δομή δεδομένων.
(Όλοι οι αριθμοί στο Pd αποθηκεύονται σαν αριθμοί κινητής υποδιαστολής 32-bit).
Τα μηνύματα αποτελούνται από ένα ή περισσότερα άτομα και χρησιμοποιούνται σαν διαταγές προς άλλα αντικείμενα.
Ένα ειδικό μήνυμα είναι αυτό χωρίς περιεχόμενο, που καλείται bang και χρησιμοποιείται για να ξεκινήσει κάποια διαδικασία
και να αρχίσει η ροή των δεδομένων, μια ιδέα παρόμοια με το πάτημα ενός κουμπιού.


installation from (vanilla)
mention extended etc


set up:
1. drivers
2. audio settings
3. test audio & midi


Creativity: δεν χρειάζεται κάποια άλλη γνώση προγραμματισμού
Intuitive Interaction:
Education: εύκολα αντιληπτή δομή

modular architecture
Όπως το Max, ο κώδικας Pd είναι αρθρωτός: αποτελείται από πολλά εξωτερικά αντικείμενα (externals), τα οποία χρησιμοποιούνται για την κατασκευή των προγραμμάτων από τον χρήστη.

Visual metaphor from analogue synthesizer patches.
Visual Programming:
intuitive interaction: connecting boxes, the diagram is the program, patches
βασική ιδέα:  αντικείμενα με εισόδους και εξόδους, συναρμολόγηση σύνθετου από επιμέρους απλά, πληροφορία και σήμα


help files are patches, help menu, online community

------
* Chapter x
midi: download SimpleSynth
