#+title: The Quest for Pure Data and SuperCollider

#+author: E. Rovithis, I. Zannos

* log

** IZ 19 Aug 2021 23:22
/At this phase (19 Aug 2021 23:20) and until further notice, please use this folder to add new texts, notes, materials./

Do this in your own branch (manos), and submit this by pushing the branch and creating pull requests.

** ER 26 Aug 2021 20:50

  η μέχρι στιγμής οργάνωση των Κεφάλαιων είναι βασισμένη:
  1) στο κείμενο που συντάξαμε κατά την πρόταση
  2) στο Pure Data tutorial που συνέταξα για τις ανάγκες του μαθήματος "Αλγοριθμική Σύνθεση και Δόμηση του Ήχου"
  3) στην οργάνωση που έχει κάνει ο Andy Farnell στο βιβλίο του "Designing Sound"

  με άλλα λόγια, έχω λάβει υπόψιν μόνο το συγκεντρωμένο υλικό για Pure Data
  και δεν έχω κοιτάξει τη δόμηση των Κεφάλαιων που κάνετε εσείς στο υλικό σας για SuperCollider. !!!!!
  Έκανα κάποιες αλλαγές ως προς τα Κεφάλαια που είχαμε καταθέσει στην πρόταση
  για ό,τι άλλο αλλάξουμε θα τροποποιήσω τη PureData ύλη αναλόγως.

  με italics στην αρχή κάθε Κεφάλαιου είναι η Σύντομη Περιγραφή που στείλαμε με την Πρόταση,
  δεν μας δεσμεύει -φαντάζομαι- την έβαλα ως οδηγό μας.

  για την ιστορία, ο Farnell δομεί -το απλοποιώ αρκετά- τα κεφάλαια του ως εξής:
  1.Getting Started: παρουσίαση του προγράμματος, εγκατάσταση, βασικές λειτουργίες, θεμελιώδη στοιχεία της γλώσσας
  2.Basic Objects: συναρμολόγηση απλών εργαλείων για διαχείριση αριθμητικών δεδομένων
  3.Audio Objects: παρουσίαση εργαλείων διαχείρισης ηχητικού σήματος, ανάπτυξη τεχνικών
  4.Abstractions: τρόποι ανάπτυξης externals, βασικά στοιχεία GUI
  5.Shaping Techniques: envelopes, filters
  6.Essential Tools: εργαλεία που αφορούν την τοποθέτηση ήχω σε χώρο και χρόνο, κονσόλα μίξης
  7.Sound Design Techniques: Additive, Subtractive, Wavetable, Waveshaping, AM, FM, Granular, Time & Pitch Shift
  8.Sound Design Examples: άφθονα και στοχευμένα παραδείγματα σχεδιασμού ηχητικών γεγονότων και διαδικασιών (πουλιά, πόρτες, βήματα, κτλ)/


* Τίτλος - ΕΙΣΑΓΩΓΗ ΣΤΟΝ ΜΟΥΣΙΚΟ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟ

** Υπότιτλος
Μουσική σύνθεση και ηχητική επεξεργασία στα ελεύθερα λογισμικά PureData και SuperCollider



* Κεφάλαιο 1 - Εισαγωγή στα Περιβάλλοντα Μουσικού Προγραμματισμού

Στο πρώτο κεφάλαιο πραγματοποιείται μια ιστορική αναδρομή στη δημιουργία και εξέλιξη
των γλωσσών μουσικού προγραμματισμού, τόσο στο σύνολό τους, όσο και ειδικότερα
ως προς τα δύο ελεύθερα λογισμικά που αποτελούν το αντικείμενο του συγγράμματος.
Παράλληλα, αναλύονται οι κοινωνικοί, πολιτικοί, και τεχνολογικοί παράγοντες που έπαιξαν καθοριστικό ρόλο
στην ανάπτυξη και διάδοση των εν λόγω δημιουργικών εργαλείων στα πεδία της έρευνας και της βιομηχανία
από τις πρώτες απόπειρες μουσικής σύνθεσης μέσω υπολογιστή μέχρι τον σύγχρονο εκδημοκρατισμό
των τεχνολογικών μέσων για ηχητική σύνθεση και επεξεργασία.

** Θεωρία
ιστορική εξέλιξη γλωσσών μουσικού προγραμματισμού με έμφαση σε SuperCollider και PureData

** Pure Data
/Θέματα: εγκατάσταση, παρουσίαση περιβάλλοντος, ροή δεδομένων, μηνύματα & αντικείμενα, κοινότητα, βοήθεια/


 Τρέχοντας το πρόγραμμα μετά την εγκατάσταση, το μοναδικό παράθυρο που βλέπουμε είναι η κονσόλα (terminal). *Figure "Terminal"*
 Η κονσόλα χρησιμεύει για τη γνωστοποίηση στον χρήστη τυχόν σφαλμάτων και την παρακολούθηση στοχευμένων δεδομένων του κώδικα.

 Στην κονσόλα βρίσκεται επίσης το πεδίο ενεργοποίησης του ήχου. *Figure "InOut"*
 Για να συντελεστεί όμως η παραγωγή οποιουδήποτε ηχητικού αποτελέσματος, θα πρέπει το Pure Date να είναι συνδεδεμένο με την κάρτα ήχου του υπολογιστή.
 Η επιλογή των κατάλληλων συσκευών Εισόδου/Εξόδου γίνεται ως εξής: /Γραμμή Εργαλειών >> Media >> Audio Settings >> Input/Output Devices/. *Figure "Settings"*
 Δοκιμή πως όλα είναι σωστά συνδεδεμένα μπορούμε να κάνουμε μέσω: /Γραμμή Εργαλειών >> Media >> Test Audio and Midi/. *Figure "TestAudio"*
 Επιλέγοντας π.χ. αριστερά τα πεδία /80/ και /tone/ θα πρέπει να ακούμε έναν τόνο 80Hz.

Σύμφωνα με τη συνήθη πρακτική των σύγχρονων προγραμμάτων, το Pure Data διαθέτει γραμμή μενού εντολών (menu bar) στην κορυφή της οθόνης. *Figure "MenuBar"*
Από εκεί μπορεί ο χρήστης να καλέσει τις βασικότερες εντολές του προγράμματος, αλλά και να δει για την κάθε μια την αντίστοιχη συντόμευση.
Στο παρόν σύγγραμμα προτείνεται ο τρόπος των συντομεύσεων, ο αναγνώστης εντούτοις μπορεί να ακολουθήσει τον τρόπο που κρίνει πιο βολικό.
Να σημειωθεί πως τα παραδείγματα υλοποίησης έχουν πραγματοποιηθεί σε περιβάλλον macOS.
Σε περιβάλλον Windows η αντιστοιχία του βασικού κουμπιού συντομεύσεων command (cmd) είναι το control (ctrl).

Για να αρχίσουμε να προγραμματίζουμε χρειάζεται να δημιουργήσουμε ένα νέο αρχείο (patch) (cmd-N).
Εμφανίζεται σε παράθυρο ένα κενό έγγραφο, το οποίο θα αναφέρεται εφ'εξής ως "πρόγραμμα". *Figure "NewPatch"*
Το κενό ως σημείο αφετηρίας δεν πρέπει να μας φοβίζει, καθώς έτσι μπορούμε χωρίς κανένα περιορισμό να δημιουργήσουμε το πρόγραμμα που επιθυμούμε.
Φανταστείτε πως έχουμε έναν λευκό καμβά που θα υποδεχτεί τα χρώματα της φαντασίας μας.

Τα προγράμματα στο Pure Data έχουν δύο (2) πιθανές καταστάσεις:
Στην κατάσταση Επεξεργασίας (Edit mode) μπορούμε να εισάγουμε και να τροποποιούμε τον κώδικα μας.
Στην κατάσταση Λειτουργίας (Run mode) μπορούμε να εκτελούμε τον κώδικα και να τον τροφοδοτούμε με δεδομένα σε πραγματικό χρόνο.
Η μετάβαση ανάμεσα στις δύο καταστάσεις γίνεται με cmd-e.
Φέρνουμε το κενό -μέχρι στιγμής- πρόγραμμα μας σε κατάσταση επεξεργασίας και παρατηρούμε την ένδειξη *edit* στην κορυφή. *Figure "EditMode"*
Είμαστε έτοιμοι να προγραμματίσουμε!


** Άσκηση: "Hello Music"















** SuperCollider


* Κεφάλαιο 2 - Πρώτα Βήματα

Στο δεύτερο κεφάλαιο περιγράφονται τα γενικά χαρακτηριστικά των δύο προγραμματιστικών περιβαλλόντων,
με έμφαση στα βασικά δομικά στοιχεία κάθε γλώσσας και τους τρόπους, με τους οποίους αυτά αλληλεπιδρούν.
Το παρόν κεφάλαιο μαζί με τα δύο επόμενα ουσιαστικά πραγματεύονται την αρχιτεκτονική,
τις αρχές λειτουργίας και το συντακτικό των λογισμικών.
Μέσω σχετικών παραδειγμάτων επιδεικνύεται η ροή επεξεργασίας της πληροφορίας
και αναλύονται οι ομοιότητες και διαφορές μεταξύ των δύο συστημάτων.


** Θεωρία
περιγραφή της φιλοσοφίας κάθε προγράμματος

** Pure Data
θεμελιώδη σωματίδια (button, toggle, messages, number boxes, arithmetic objects)
Άσκηση: Επαναλαμβανόμενος Μετρητής Ενεργειών (bangs) (μόνο με arithmetic tools objects)

** SuperCollider


* Κεφάλαιο 3 - Βασικά Στοιχεία και Δόμηση Μουσικών Προγραμμάτων

Στο τρίτο κεφάλαιο περιγράφονται τα βασικά επιμέρους στοιχεία κάθε γλώσσας,
και περιγράφονται οι αρχές με τις οποίες συνδυάζονται για την δημιουργία μουσικών προγραμμάτων.
Επίσης εισάγονται οι αρχές επεξεργασίας ψηφιακού σήματος και του προγραμματισμού,
όπως σήμα, buffer, γεννήτρια, είσοδος, έξοδος, δίαυλος, μεταβλητή, συνάρτηση κ.α.
Στόχος είναι να γίνει κατανοητό μέσω παραδειγμάτων πως ο συνδυασμός των στοιχείων αυτών
μπορεί να οδηγήσει σε ένα μουσικό ή άλλο ηχητικό αποτέλεσμα.

** Θεωρία
(περιγραφή βασικών μονάδων κάθε προγράμματος)

** Pure Data
βασικά αντικείμενα (select, metro, timer)
Άσκηση: μετρονόμος σε bpm

** SuperCollider


* Κεφάλαιο 8 - Το Ηχητικό Δείγμα

Στο όγδοο κεφάλαιο το ενδιαφέρον εστιάζεται σε τεχνικές ηχητικής σύνθεσης
βασισμένες στην εισαγωγή και επεξεργασία ηχητικού δείγματος.
Παρουσιάζεται η ιστορική εξέλιξη του sampling από τις πρώτες μεθοδικές προσεγγίσεις
μέχρι τη σύγχρονη τεχνολογία αιχμής, και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα
αντίστοιχα εργαλεία εισαγωγής, αναπαραγωγής, και τεμαχισμού δείγματος, και ανακατανομής τμημάτων.
Έπειτα αναλύονται και υλοποιούνται τεχνικές επεξεργασίας πλάτους σήματος,
όπως η κανονικοποίηση (normalization), η συμπίεση (compression) και η διόγκωση (expansion).

** Θεωρία

δειγματοληψία

** Pure Data

αντικείμενα καταγραφής και αναπαραγωγής, πίνακες τιμών
Άσκηση: sampler και chopper με μεταβλητή playback speed

** SuperCollider


* Κεφάλαιο 4 - Ντετερμινισμός και Τυχαιοκρατία στη Μουσική Εκτέλεση

Στο τέταρτο κεφάλαιο αναλύονται αφενός η φιλοσοφία διαφορετικών μοντέλων παραγωγής και οργάνωσης των δεδομένων
και αφετέρου η πραγμάτωσή τους στα δύο προγραμματιστικά περιβάλλοντα.
Συγκεκριμένα, τα μοντέλα αυτά περιλαμβάνουν ντετερμινιστικές, πιθανοκρατικές, και τυχαιοκρατικές προγραμματιστικές δομές.
Το θεωρητικό μέρος του κεφαλαίου εστιάζει στην ιστορική εξέλιξη τέτοιων δομών,
καθώς και στην εφαρμογή τους για τη δημιουργία έργων ψηφιακής τέχνης,
ενώ το πρακτικό μέρος αναλύει τη χρήση λογικών ελεγκτών για τον συσχετισμό των επιμέρους στοιχείων
και τη συναρμολόγηση συστημάτων σύμφωνα με τις αρχές κάθε οργάνωσης.

** Θεωρία
τυχαιότητα

** Pure Data
random, relational & logical operators
Άσκηση: γεννήτρια τυχαίας παραγωγής ρυθμικών μοτίβων

** SuperCollider


* Κεφάλαιο 5 - Αρχές Σύνθεσης και Επεξεργασίας Ήχου

Στο πέμπτο κεφάλαιο περιγράφονται και στα δύο προγραμματιστικά περιβάλλοντα οι βασικές αρχές ηχητικής σύνθεσης και επεξεργασίας.
Συγκεκριμένα αναλύονται οι εσωτερικές διαδικασίες παραγωγής ήχου μέσω ηλεκτρονικού υπολογιστή
από το πιο απλό είδος ταλάντωσης, δηλαδή της ημιτονοειδούς ταλάντωσης, και πιο σύνθετων κυματομορφών,
όπως της πριονωτής, της τριγωνικής και της τετράγωνης κυματομορφής, έως την παραγωγή θορύβου ως πρωτογενούς ηχητικού υλικού.
Αναφέρονται οι ηχητικές ιδιότητες της θεμελιώδους συχνότητας και των αρμονικών,
καθώς και οι ακουστικές διαστάσεις των διαφορετικών ειδών θορύβου βάσει του συχνοτικού φάσματος.
Τέλος, ο αναγνώστης καθοδηγείται προς τη δημιουργία μιας γεννήτριας ταλαντωτών.
Το παρόν κεφάλαιο μαζί με τα τρία επόμενα εστιάζει στις ηχητικές πηγές και σε απλούς τρόπους επεξεργασίας τους.

** Θεωρία
από την αρμονική ταλάντωση στον θόρυβο

** Pure Data
γεννήτριες ταλαντωτών και θορύβου, περιβάλλουσα έντασης
Άσκηση: γεννήτρια με τυχαία επιλογή εκ των βασικών κυματομορφών

** SuperCollider


* Κεφάλαιο 7 - Μουσική Δόμηση του Ήχου

Στο έβδομο κεφάλαιο αναλύεται η διαχείριση midi πληροφοριών, από τη μετατροπή του μεγέθους της συχνότητας σε midi τιμή,
μέχρι τη δημιουργία και στις δύο γλώσσες προγραμματισμού μιας γεννήτριας ηχητικών συμβάντων
με δυνατότητες ενεργοποίησης των midi ήχων του υπολογιστή και οργάνωσής τους σε ακολουθίες
κατά τα πρότυπα διαφορετικών μουσικών κλιμάκων.
Επεξηγούνται οι προγραμματιστικές έννοιες των μοτίβων (patterns), επαναλαμβανόμενων διεργασιών (routines and tasks),
και των πληροφοριακών ροών (streams), ως προς τη λειτουργία τους για τη διαχείριση ηχητικών δεδομένων.
Επιπλέον, περιγράφονται οι έννοιες της οκτάβας και της μουσικής κλίμακας,
και αναφέρεται η γέννηση και ο σημαντικός αντίκτυπος της midi τεχνολογίας στη μουσική βιομηχανία.
Τέλος, συνδυάζονται προηγούμενες γνώσεις σχετικές με τα μοντέλα πιθανοκρατικής διαχείρισης της πληροφορίας
για τη δημιουργία εργαλείου για μουσικό αυτοσχεδιασμό υποβοηθούμενο από τον υπολογιστή.

** Θεωρία
νότες, πρωτόκολλο midi

** Pure Data
αντικείμενα διαχείρισης midi
Άσκηση: γεννήτρια τυχαίων τονικών μοτίβων

** SuperCollider


* Κεφάλαιο 6 - Προσθετική και Αφαιρετική Σύνθεση

Στο έκτο κεφάλαιο πραγματοποιείται επίδειξη των τεχνικών της προσθετικής και αφαιρετικής σύνθεσης.
Αναλύονται στα δύο προγραμματιστικά περιβάλλοντα οι διαδικασίες συχνοτικής επεξεργασίας
τόσο μέσω της πρόσθεσης ταλαντωτών, όσο και μέσω φίλτρων συχνοτικής αποσιώπησης και ενίσχυσης.
Τέλος, ο αναγνώστης καθοδηγείται προς την υλοποίηση γεννήτριας προσθετικής επεξεργασίας πολλαπλών ταλαντωτών,
και παραγωγής θορύβου με δυνατότητα συχνοτικής επεξεργασίας μέσω εργαλείου παραμετροποιημένης ισοστάθμισης.

** Θεωρία
Προσθετική και Αφαιρετική Σύνθεση

** Pure Data
αντικείμενα οπτικής παρατήρησης, φίλτρα
Άσκηση: γεννήτρια για προσθήκη αρμονικών και φιλτράρισμα θορύβου.

** SuperCollider


* Κεφάλαιο 10 - Τεχνικές Διαμόρφωσης Σήματος

Στο δέκατο κεφάλαιο παρουσιάζονται ευρέως διαδεδομένες τεχνικές διαμόρφωσης του ηχητικού σήματος,
συγκεκριμένα η Διαμόρφωση Πλάτους (Amplitude Modulation - AM), η Διαμόρφωση Δακτυλίου (Ring Modulation),
η Διαμόρφωση Συχνότητας (Frequency Modulation - FM), και οι Περιβάλλουσες (Envelopes).
Έπειτα από μια ιστορική αναδρομή στην εξέλιξή τους, αναλύονται οι βασικές αρχές λειτουργίας τους
και περιγράφεται η ανάπτυξη των αντίστοιχων επεξεργαστικών εργαλείων.

** Θεωρία
AM, FM

** Pure Data
εργαλεία AM FM
Άσκηση: ενσωμάτωση στο όργανο

** SuperCollider


* Κεφάλαιο 12 - Προηγμένες Τεχνικές Σύνθεσης

Στο δωδέκατο κεφάλαιο αναλύονται προηγμένες τεχνικές ηχητικής σύνθεσης και
υλοποιούνται τα αντίστοιχα εργαλεία στα δύο προγραμματιστικά περιβάλλοντα.
Συγκεκριμένα, το ενδιαφέρον εστιάζεται στην Κοκκώδη Σύνθεση (Granular Synthesis),
στη Σύνθεση Μέσω Πινάκων (Wavetable Synthesis),
και στον Διακριτό Μετασχηματισμό Fourier (Fast Fourier Transform).

** Θεωρία
granular, wavetable, FFT

** Pure Data
granular, wavetable, waveshaping?
Άσκηση: ενσωμάτωση στο instrument

** SuperCollider


* Κεφάλαιο 11 - Τεχνικές Ανάδρασης

Στο ενδέκατο κεφάλαιο αναλύονται τεχνικές επεξεργασίας ηχητικού σήματος βασισμένες
στην ανάδραση που δημιουργεί η μεταβαλλόμενη χρονική του καθυστέρηση και ανατροφοδότηση.
Συγκεκριμένα, επεξηγούνται και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα
οι τεχνικές επεξεργασίας delay, echo, flanger, και reverb.

** Θεωρία
καθυστέρηση και ανατροφοδότηση, FIR και IIR φίλτρα

** Pure Data
αντικείμενα καθυστέρησης
Άσκηση: ενσωμάτωση στο όργανο

** SuperCollider


* Κεφάλαιο 13 - Σχεδιασμός Περιβάλλοντος Διεπαφής

Στο δέκατο τρίτο κεφάλαιο εξετάζονται θέματα σχεδιασμού του περιβάλλοντος διεπαφής
ως προς τη χρηστικότητα και φιλικότητά του προς τον τελικό χρήστη.
Εξετάζονται οι δυνατότητες κάθε γλώσσας για τη σε-πραγματικό-χρόνο εισαγωγή δεδομένων,
τη συνδεσιμότητα με εξωτερικούς ελεγκτές μέσω πρωτοκόλλου OSC, την οπτική οργάνωση
μέσω της χρήσης υποστηρικτικών γραφικών, και την ενσωμάτωση των υλοποιημένων εργαλείων
ως αυτόνομες εφαρμογές σε άλλες πλατφόρμες (VSTplugins).

** Θεωρία
GUI

** Pure Data
OSC, abstractions, plugins
Άσκηση: ενσωμάτωση σε όργανο

** SuperCollider





* Κεφάλαιο 14 - Αυτοσχεδιασμός και Αυτόματα

Στο δέκατο τέταρτο κεφάλαιο εξετάζονται θέματα υποβοήθησης της μουσικής εκτέλεσης
μέσω του ηλεκτρονικού υπολογιστή.
Αναφέρονται τεχνικές καταγραφής, ανάλυσης και μίμηση της εκτέλεσης,
καθώς και αυτοματοποιημενης αλγοριθμικής οργάνωσης.

** Θεωρία
 generative music, AI

** Pure Data
Άσκηση: ενσωμάτωση σε όργανο

** SuperCollider





* Κεφάλαιο 0 - Οπτική Αναπαράσταση του Ήχου

Σημαντική παράμετρος της μετάβασης σε προηγμένες τεχνικές ηχητικής σύνθεσης είναι
να αποκτήσει ο διδασκόμενος τα απαραίτητα εργαλεία επίβλεψης των ηχητικών χαρακτηριστικών,
ώστε να κατανοήσει καλύτερα τις διαδικασίες της μεταμόρφωσής του.
Ως εκ τούτου, στο ένατο κεφάλαιο παρουσιάζονται οι δυνατότητες των δύο λογισμικών
ως προς τη δυνατότητα οπτικής απεικόνισης και επίβλεψης του ήχου.
Τα εργαλεία απεικόνισης που αναλύονται αφορούν τόσο στη δυναμική της έντασης, όσο και στο συχνοτικό φάσμα του ήχου.

*** Θεωρία

*** Pure Data

*** SuperCollider
