#+title: The Quest for Pure Data and SuperCollider

#+author: E. Rovithis, I. Zannos

* log

** IZ 19 Aug 2021 23:22
/At this phase (19 Aug 2021 23:20) and until further notice, please use this folder to add new texts, notes, materials./

Do this in your own branch (manos), and submit this by pushing the branch and creating pull requests.

** ER 26 Aug 2021 20:50

  η μέχρι στιγμής οργάνωση των Κεφάλαιων είναι βασισμένη:
  1) στο κείμενο που συντάξαμε κατά την πρόταση
  2) στο Pure Data tutorial που συνέταξα για τις ανάγκες του μαθήματος "Αλγοριθμική Σύνθεση και Δόμηση του Ήχου"
  3) στην οργάνωση που έχει κάνει ο Andy Farnell στο βιβλίο του "Designing Sound"

  με άλλα λόγια, έχω λάβει υπόψιν μόνο το συγκεντρωμένο υλικό για Pure Data
  και δεν έχω κοιτάξει τη δόμηση των Κεφάλαιων που κάνετε εσείς στο υλικό σας για SuperCollider. !!!!!
  Έκανα κάποιες αλλαγές ως προς τα Κεφάλαια που είχαμε καταθέσει στην πρόταση
  για ό,τι άλλο αλλάξουμε θα τροποποιήσω τη PureData ύλη αναλόγως.

  με italics στην αρχή κάθε Κεφάλαιου είναι η Σύντομη Περιγραφή που στείλαμε με την Πρόταση,
  δεν μας δεσμεύει -φαντάζομαι- την έβαλα ως οδηγό μας.

  για την ιστορία, ο Farnell δομεί -το απλοποιώ αρκετά- τα κεφάλαια του ως εξής:
  1.Getting Started: παρουσίαση του προγράμματος, εγκατάσταση, βασικές λειτουργίες, θεμελιώδη στοιχεία της γλώσσας
  2.Basic Objects: συναρμολόγηση απλών εργαλείων για διαχείριση αριθμητικών δεδομένων
  3.Audio Objects: παρουσίαση εργαλείων διαχείρισης ηχητικού σήματος, ανάπτυξη τεχνικών
  4.Abstractions: τρόποι ανάπτυξης externals, βασικά στοιχεία GUI
  5.Shaping Techniques: envelopes, filters
  6.Essential Tools: εργαλεία που αφορούν την τοποθέτηση ήχω σε χώρο και χρόνο, κονσόλα μίξης
  7.Sound Design Techniques: Additive, Subtractive, Wavetable, Waveshaping, AM, FM, Granular, Time & Pitch Shift
  8.Sound Design Examples: άφθονα και στοχευμένα παραδείγματα σχεδιασμού ηχητικών γεγονότων και διαδικασιών (πουλιά, πόρτες, βήματα, κτλ)/


* Τίτλος - ΕΙΣΑΓΩΓΗ ΣΤΟΝ ΜΟΥΣΙΚΟ ΠΡΟΓΡΑΜΜΑΤΙΣΜΟ

** Υπότιτλος
Μουσική σύνθεση και ηχητική επεξεργασία στα ελεύθερα λογισμικά Pure Data και SuperCollider



* Κεφάλαιο 1 - Εισαγωγή στα Περιβάλλοντα Μουσικού Προγραμματισμού

** Προοίμιο

/ιστορική αναδρομή στη δημιουργία και εξέλιξη των γλωσσών μουσικού προγραμματισμού με έμφαση σε Pd και SC/
/κοινωνικοί, πολιτικοί, και τεχνολογικοί παράγοντες που έπαιξαν καθοριστικό ρόλο στην ανάπτυξη και διάδοση των εν λόγω εργαλείων/
/πρώτες απόπειρες μουσικής σύνθεσης μέσω υπολογιστή μέχρι τον σύγχρονο εκδημοκρατισμό των τεχνολογικών μέσων για ηχητική σύνθεση και επεξεργασία/

/Θέματα Pd: εγκατάσταση, παρουσίαση περιβάλλοντος, ροή δεδομένων, μηνύματα & αντικείμενα, κοινότητα, βοήθεια/

** Άσκηση: "Hello Music"


*** Pure Data

 Τρέχοντας το πρόγραμμα μετά την εγκατάσταση, το μοναδικό παράθυρο που βλέπουμε είναι η κονσόλα (terminal). *Figure "Terminal"*
 Η κονσόλα χρησιμεύει για τη γνωστοποίηση στον χρήστη τυχόν σφαλμάτων και την παρακολούθηση στοχευμένων δεδομένων του κώδικα.

 Στην κονσόλα βρίσκεται επίσης το πεδίο ενεργοποίησης του ήχου. *Figure "InOut"*
 Για να συντελεστεί όμως η παραγωγή οποιουδήποτε ηχητικού αποτελέσματος, θα πρέπει το Pure Date να είναι συνδεδεμένο με την κάρτα ήχου του υπολογιστή.
 Η επιλογή των κατάλληλων συσκευών Εισόδου/Εξόδου γίνεται ως εξής: /Γραμμή Εργαλειών >> Media >> Audio Settings >> Input/Output Devices/. *Figure "Settings"*
 Δοκιμή πως όλα είναι σωστά συνδεδεμένα μπορούμε να κάνουμε μέσω: /Γραμμή Εργαλειών >> Media >> Test Audio and Midi/. *Figure "TestAudio"*
 Επιλέγοντας π.χ. αριστερά τα πεδία /80/ και /tone/ θα πρέπει να ακούμε έναν τόνο 80Hz.

Σύμφωνα με τη συνήθη πρακτική των σύγχρονων προγραμμάτων, το Pure Data διαθέτει γραμμή μενού εντολών (menu bar) στην κορυφή της οθόνης. *Figure "MenuBar"*
Από εκεί μπορεί ο χρήστης να καλέσει τις βασικότερες εντολές του προγράμματος, αλλά και να δει για την κάθε μια την αντίστοιχη συντόμευση.
Στο παρόν σύγγραμμα προτείνεται ο τρόπος των συντομεύσεων, οι οποίες θα αναγράφονται σε παρενθέσεις.
Εντούτοις, ο αναγνώστης μπορεί να ακολουθήσει όποιον τρόπο κρίνει πιο βολικό.

Να σημειωθεί, επίσης, πως τα παραδείγματα υλοποίησης έχουν πραγματοποιηθεί σε περιβάλλον macOS.
Σε περιβάλλον Windows η αντιστοιχία του βασικού κουμπιού συντομεύσεων command (cmd) είναι το control (ctrl).

Για να αρχίσουμε να προγραμματίζουμε χρειάζεται να δημιουργήσουμε ένα νέο αρχείο (patch) (cmd-N).
Εμφανίζεται σε παράθυρο ένα κενό έγγραφο, το οποίο θα αναφέρεται εφ'εξής ως "πρόγραμμα". *Figure "NewPatch"*
Το κενό ως σημείο αφετηρίας δεν πρέπει να μας φοβίζει, καθώς έτσι μπορούμε χωρίς κανένα περιορισμό να δημιουργήσουμε το πρόγραμμα που επιθυμούμε.
Φανταστείτε πως έχουμε έναν λευκό καμβά που θα υποδεχτεί τα χρώματα της φαντασίας μας.

Τα προγράμματα στο Pure Data έχουν δύο (2) πιθανές καταστάσεις:
Στην κατάσταση Επεξεργασίας (Edit mode) μπορούμε να εισάγουμε και να τροποποιούμε τον κώδικα μας.
Στην κατάσταση Λειτουργίας (Run mode) μπορούμε να εκτελούμε τον κώδικα και να τον τροφοδοτούμε με δεδομένα σε πραγματικό χρόνο.
Η μετάβαση ανάμεσα στις δύο καταστάσεις γίνεται με (cmd-Ε).
Φέρνουμε το κενό -μέχρι στιγμής- πρόγραμμα μας σε κατάσταση επεξεργασίας και παρατηρούμε την ένδειξη *edit* στην κορυφή. *Figure "EditMode"*
Είμαστε έτοιμοι να προγραμματίσουμε!

Για την πρώτη μας άσκηση θα παραφράσουμε την -κλασική πια στην εκμάθηση γλωσσών προγραμματισμού- άσκηση εμφάνισης του μηνύματος "Hello World".
Αντ'αυτού επιλέγουμε να εμφανίσουμε "Hello Music" και μάλιστα η εντολή αυτή να εκτελείται αυτόματα με το άνοιγμα του προγράμματος,
στο οποίο θα υλοποιήσουμε μέχρι το τέλος αυτού του συγγράμματος το όργανο ηχητικής δημιουργίας.

Για την υλοποίηση της Άσκησης θα χρειαστούμε τα εξής 3 αντικείμενα: message, print, loadbang

Εισάγουμε στο πρόγραμμα μας ένα αντικείμενο message (cmd-2).
Παρατηρούμε πως το αντικείμενο κολλάει στον κέρσορα μας και χρειάζεται να κλικάρουμε σε όποιο σημείο του καμβά θέλουμε να το αποθέσουμε.
Παρατηρούμε επίσης πως σε δύο σημεία, ένα πάνω και ένα κάτω, το περίγραμμα του αντικειμένου είναι πιο έντονο.
Το πάνω σημείο αποτελεί την είσοδο του αντικειμένου, ενώ το κάτω την έξοδο του.
Συνεπώς, το αντικείμενο message έχει μία είσοδο και μία έξοδο, ώστε να επικοινωνεί με άλλα αντικείμενα.
Γράφουμε μέσα στο πλαίσιο του αντικειμένου τη φράση "Hello Music" και κλικάρουμε οπουδήποτε έξω από αυτό στον καμβά.

Το μήνυμα αυτό χρειάζεται ένα αντικείμενο, το οποίο θα φροντίσει για την εμφάνιση του μηνύματος στην κονσόλα.
Εισάγουμε στο πρόγραμμα ένα αντικείμενο print (cmd-1 και έπειτα πληκτρολογούμε στο πεδίο του αντικειμένου "print")
To αντικείμενο print έχει μόνο μία είσοδο, με την οποία πρέπει να ενώσουμε την έξοδο του message.

Η διαδικασία σύνδεσης δύο αντικειμένων συντελείται ως εξής:
Κρατώντας τον κέρσορα πάνω από μια έξοδο, αυτός παίρνει τη μορφή κύκλου.
Κλικάρουμε (δεξί κλικ) και κρατώντας πατημένο το κουμπί του ποντικιού (ή την επιφάνεια του touchpad) σέρνουμε προς την επιθυμητή είσοδο.
Όταν εμφανιστεί πάλι κύκλος, αφήνουμε το κουμπί, για να ολοκληρωθεί η σύνδεση.

Τώρα που συνδέσαμε το message με το print κλειδώνουμε το πρόγραμμα και πατάμε το message. *Figure "FirstConnection"*
Θα δούμε να εμφανίζεται στην κονσόλα μας το επιθυμητό μήνυμα. *Figure "HelloMusic"*
Για να εμφανίζεται το μήνυμα κάθε φορά που ανοίγουμε το πρόγραμμα, χρειαζόμαστε ένα αντικείμενο που να μιμείται το χειροκίνητο πάτημα του message.
Ξεκλειδώνουμε το πρόγραμμα και εισάγουμε το αντικείμενο loadbang, όπως κάναμε πριν με το αντικείμενο print.
Ενώνουμε την έξοδο του loadbang με την είσοδο του message. *Figure "FirstSystem"*
Κλειδώνουμε το πρόγραμμα και το αποθηκεύουμε με την ενδεικτική ονομασία "MyPdSynth" (μενού εντολών >> save as).
Την επόμενη φορά που θα ανοίξουμε το πρόγραμμα, το μήνυμα θα εμφανιστεί αυτόματα στην κονσόλα.


*** SuperCollider



* Κεφάλαιο 2 - Πρώτα Βήματα

** Προοίμιο

/γενικά χαρακτηριστικά των δύο περιβαλλόντων με έμφαση στα δομικά στοιχεία και τους τρόπους που αυτά αλληλεπιδρούν/
/αρχιτεκτονική, αρχές λειτουργίας, και συντακτικό/

/θέματα Pd: θεμελιώδη σωματίδια (button, toggle, messages, number boxes, arithmetic objects)/

** Άσκηση: "Count Me In"


*** Pure Data

Η γλώσσα του Pd μπορεί να διακριθεί σε εργαλεία που αφορούν τη διαχείριση αριθμητικών δεδομένων και εργαλεία που αφορούν τη διαχείριση σήματος.
Στο παρόν κεφάλαιο θα εστιάσουμε στην πρώτη κατηγορία.

Βασική θέση στο λεξιλόγιο της γλώσσας καταλαμβάνει το εργαλείο bang.(shift-cmd-B)
Ουσιαστικά αποτελεί ένα εικονικό κόμβιο που εκφράζει μια ενέργεια. (ή εικονικό κόμβιο, φορέας εν δυνάμει ενέργειας)
Πατώντας το κόμβιο η ενέργεια αυτή μεταδίδεται από την έξοδο στα συνδεδεμένα αντικείμενα.
Επιπλέον της χειροκίνητης ενεργοποίησης, το κόμβιο ενεργοποιείται και άνωθεν από τα συνδεδεμένα αντικείμενα.
Συνεπώς, το bang έχει μια είσοδο και μια έξοδο. *Figure "Bang"*

Άλλο βασικό αντικείμενο είναι το number (cmd-3), το οποίο απεικονίζει και μεταδίδει αριθμητικά δεδομένα.
Μπορεί να ενεργοποιηθεί χειροκίνητα, πληκτρολογώντας μια τιμή στο πεδίο και πατώντας το enter,
ή κλικάροντας και σέρνοντας πατημένα προς πάνω ή κάτω για αύξηση και μείωση τιμών αντίστοιχα.
Χρήσιμο στη χειροκίνητη λειτουργία είναι να θέσουμε ελάχιστο και μέγιστο όριο στις αποτυπώμενες τιμές,
και με αυτή την αφορμή να δούμε πώς μπορούμε γενικά να επέμβουμε στις ιδιότητες των αντικειμένων.

Με δεξί κλικ στο number εμφανίζεται η επιλογή properties. *Figure "Properties"*
Εδώ μπορούμε να τροποποιήσουμε τις τιμές και καταστάσεις διάφορων εσωτερικών παραμέτρων.
Σε αυτή την περίπτωση ορίζουμε ελάχιστη και μέγιστη τιμή του number στην κατηγορία Limits και τα πεδία Lower και Upper.
Να σημειωθεί εδώ πως κάποια αντικείμενα δεν δίνουν την επιλογή τροποποίησης των ιδιοτήτων τους.

Το αντικείμενο number δέχεται τιμές και από άλλα αντικείμενα, το καθένα από τα οποία επενεργεί με συγκεκριμένο τρόπο.
Ας δούμε το πρόγραμμα στην Εικόνα *Figure "Number"*
Δύο messages και ένα bang είναι συνδεδεμένα σε ένα number, και αυτό με τη σειρά του συνδέεται σε ένα print.
Με το bang στέλνουμε την τρέχουσα τιμή του number στο print.
Πατάμε το message με τον αριθμό "7" και παρατηρούμε πως εμφανίζεται στο number και στην κονσόλα μας.
Αντίθετα, πατώντας τo message "set 9" παρατηρούμε πως ο αριθμός "9" εμφανίζεται μόνο στο number.
Αυτό συμβαίνει, επειδή το πρόθεμα "set" σε ένα message έχει την ιδιότητα να διαμοιράζει την πληροφορία μόνο στο επόμενο στάδιο,
χωρίς να την πυροδοτεί περαιτέρω, κι έτσι αυτή δεν φτάνει στο print.

Οι αριθμητικοί τελεστές είναι αντικείμενα, με τα οποία πραγματοποιούμε αριθμητικές πράξεις,
συγκεκριμένα πρόσθεση, αφαίρεση, πολλαπλασιασμό, διαίρεση, και ύψωση σε δύναμη. *Figure "Math"*
Παρατηρούμε πως τα αντικείμενα αυτά έχουν δύο εισόδους.
Κάθε είσοδος πλην της αριστερής ονομάζεται "κρύα" και έχει τη λειτουργία να αποθηκεύει την εισαγόμενη πληροφορία,
χωρίς όμως να πυροδοτεί την έξοδο του αντικειμένου.
Η αριστερή είσοδος ονομάζεται "ζεστή" και, δεχόμενη πληροφορία, εκτελεί την πράξη και πυροδοτεί την έξοδο.
Οι αριθμητικοί τελεστές έχουν αρχική τιμή μηδέν.
Κάθε τιμή που θα εισαχθεί στην κρύα είσοδο, θα αποθηκευτεί στη θέση της αρχικής, χωρίς να εξάγει αποτέλεσμα.
Η τιμή που εισαχθεί στη ζεστή είσοδο, θα πραγματοποιήσει την πράξη και θα εξάγει αποτέλεσμα.
Να σημειωθεί εδώ πως η αρχική τιμή μπορεί να οριστεί ως παράμετρος του αντικειμένου κατά την κλήση του.
Στην εικόνα *Figure "MathAct"* βλέπουμε ένα αντικείμενο διαίρεσης με αρχική αναγραφόμενη τιμή "3".
Κάθε τιμή που εισάγεται στη ζεστή είσοδο θα διαιρεθεί με αυτή την αρχική τιμή, εκτός αν έχει αντικατασταθεί από άλλη στην κρύα είσοδο.






*** SuperCollider



* Κεφάλαιο 3 - Βασικά Στοιχεία και Δόμηση Μουσικών Προγραμμάτων

Στο τρίτο κεφάλαιο περιγράφονται τα βασικά επιμέρους στοιχεία κάθε γλώσσας,
και περιγράφονται οι αρχές με τις οποίες συνδυάζονται για την δημιουργία μουσικών προγραμμάτων.
Επίσης εισάγονται οι αρχές επεξεργασίας ψηφιακού σήματος και του προγραμματισμού,
όπως σήμα, buffer, γεννήτρια, είσοδος, έξοδος, δίαυλος, μεταβλητή, συνάρτηση κ.α.
Στόχος είναι να γίνει κατανοητό μέσω παραδειγμάτων πως ο συνδυασμός των στοιχείων αυτών
μπορεί να οδηγήσει σε ένα μουσικό ή άλλο ηχητικό αποτέλεσμα.

** Θεωρία
(περιγραφή βασικών μονάδων κάθε προγράμματος)

** Pure Data
βασικά αντικείμενα (select, metro, timer)
Άσκηση: μετρονόμος σε bpm

** SuperCollider


* Κεφάλαιο 8 - Το Ηχητικό Δείγμα

Στο όγδοο κεφάλαιο το ενδιαφέρον εστιάζεται σε τεχνικές ηχητικής σύνθεσης
βασισμένες στην εισαγωγή και επεξεργασία ηχητικού δείγματος.
Παρουσιάζεται η ιστορική εξέλιξη του sampling από τις πρώτες μεθοδικές προσεγγίσεις
μέχρι τη σύγχρονη τεχνολογία αιχμής, και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα
αντίστοιχα εργαλεία εισαγωγής, αναπαραγωγής, και τεμαχισμού δείγματος, και ανακατανομής τμημάτων.
Έπειτα αναλύονται και υλοποιούνται τεχνικές επεξεργασίας πλάτους σήματος,
όπως η κανονικοποίηση (normalization), η συμπίεση (compression) και η διόγκωση (expansion).

** Θεωρία

δειγματοληψία

** Pure Data

αντικείμενα καταγραφής και αναπαραγωγής, πίνακες τιμών
Άσκηση: sampler και chopper με μεταβλητή playback speed

** SuperCollider


* Κεφάλαιο 4 - Ντετερμινισμός και Τυχαιοκρατία στη Μουσική Εκτέλεση

Στο τέταρτο κεφάλαιο αναλύονται αφενός η φιλοσοφία διαφορετικών μοντέλων παραγωγής και οργάνωσης των δεδομένων
και αφετέρου η πραγμάτωσή τους στα δύο προγραμματιστικά περιβάλλοντα.
Συγκεκριμένα, τα μοντέλα αυτά περιλαμβάνουν ντετερμινιστικές, πιθανοκρατικές, και τυχαιοκρατικές προγραμματιστικές δομές.
Το θεωρητικό μέρος του κεφαλαίου εστιάζει στην ιστορική εξέλιξη τέτοιων δομών,
καθώς και στην εφαρμογή τους για τη δημιουργία έργων ψηφιακής τέχνης,
ενώ το πρακτικό μέρος αναλύει τη χρήση λογικών ελεγκτών για τον συσχετισμό των επιμέρους στοιχείων
και τη συναρμολόγηση συστημάτων σύμφωνα με τις αρχές κάθε οργάνωσης.

** Θεωρία
τυχαιότητα

** Pure Data
random, relational & logical operators
Άσκηση: γεννήτρια τυχαίας παραγωγής ρυθμικών μοτίβων

** SuperCollider


* Κεφάλαιο 5 - Αρχές Σύνθεσης και Επεξεργασίας Ήχου

Στο πέμπτο κεφάλαιο περιγράφονται και στα δύο προγραμματιστικά περιβάλλοντα οι βασικές αρχές ηχητικής σύνθεσης και επεξεργασίας.
Συγκεκριμένα αναλύονται οι εσωτερικές διαδικασίες παραγωγής ήχου μέσω ηλεκτρονικού υπολογιστή
από το πιο απλό είδος ταλάντωσης, δηλαδή της ημιτονοειδούς ταλάντωσης, και πιο σύνθετων κυματομορφών,
όπως της πριονωτής, της τριγωνικής και της τετράγωνης κυματομορφής, έως την παραγωγή θορύβου ως πρωτογενούς ηχητικού υλικού.
Αναφέρονται οι ηχητικές ιδιότητες της θεμελιώδους συχνότητας και των αρμονικών,
καθώς και οι ακουστικές διαστάσεις των διαφορετικών ειδών θορύβου βάσει του συχνοτικού φάσματος.
Τέλος, ο αναγνώστης καθοδηγείται προς τη δημιουργία μιας γεννήτριας ταλαντωτών.
Το παρόν κεφάλαιο μαζί με τα τρία επόμενα εστιάζει στις ηχητικές πηγές και σε απλούς τρόπους επεξεργασίας τους.

** Θεωρία
από την αρμονική ταλάντωση στον θόρυβο

** Pure Data
γεννήτριες ταλαντωτών και θορύβου, περιβάλλουσα έντασης
Άσκηση: γεννήτρια με τυχαία επιλογή εκ των βασικών κυματομορφών

** SuperCollider


* Κεφάλαιο 7 - Μουσική Δόμηση του Ήχου

Στο έβδομο κεφάλαιο αναλύεται η διαχείριση midi πληροφοριών, από τη μετατροπή του μεγέθους της συχνότητας σε midi τιμή,
μέχρι τη δημιουργία και στις δύο γλώσσες προγραμματισμού μιας γεννήτριας ηχητικών συμβάντων
με δυνατότητες ενεργοποίησης των midi ήχων του υπολογιστή και οργάνωσής τους σε ακολουθίες
κατά τα πρότυπα διαφορετικών μουσικών κλιμάκων.
Επεξηγούνται οι προγραμματιστικές έννοιες των μοτίβων (patterns), επαναλαμβανόμενων διεργασιών (routines and tasks),
και των πληροφοριακών ροών (streams), ως προς τη λειτουργία τους για τη διαχείριση ηχητικών δεδομένων.
Επιπλέον, περιγράφονται οι έννοιες της οκτάβας και της μουσικής κλίμακας,
και αναφέρεται η γέννηση και ο σημαντικός αντίκτυπος της midi τεχνολογίας στη μουσική βιομηχανία.
Τέλος, συνδυάζονται προηγούμενες γνώσεις σχετικές με τα μοντέλα πιθανοκρατικής διαχείρισης της πληροφορίας
για τη δημιουργία εργαλείου για μουσικό αυτοσχεδιασμό υποβοηθούμενο από τον υπολογιστή.

** Θεωρία
νότες, πρωτόκολλο midi

** Pure Data
αντικείμενα διαχείρισης midi
Άσκηση: γεννήτρια τυχαίων τονικών μοτίβων

** SuperCollider


* Κεφάλαιο 6 - Προσθετική και Αφαιρετική Σύνθεση

Στο έκτο κεφάλαιο πραγματοποιείται επίδειξη των τεχνικών της προσθετικής και αφαιρετικής σύνθεσης.
Αναλύονται στα δύο προγραμματιστικά περιβάλλοντα οι διαδικασίες συχνοτικής επεξεργασίας
τόσο μέσω της πρόσθεσης ταλαντωτών, όσο και μέσω φίλτρων συχνοτικής αποσιώπησης και ενίσχυσης.
Τέλος, ο αναγνώστης καθοδηγείται προς την υλοποίηση γεννήτριας προσθετικής επεξεργασίας πολλαπλών ταλαντωτών,
και παραγωγής θορύβου με δυνατότητα συχνοτικής επεξεργασίας μέσω εργαλείου παραμετροποιημένης ισοστάθμισης.

** Θεωρία
Προσθετική και Αφαιρετική Σύνθεση

** Pure Data
αντικείμενα οπτικής παρατήρησης, φίλτρα
Άσκηση: γεννήτρια για προσθήκη αρμονικών και φιλτράρισμα θορύβου.

** SuperCollider


* Κεφάλαιο 10 - Τεχνικές Διαμόρφωσης Σήματος

Στο δέκατο κεφάλαιο παρουσιάζονται ευρέως διαδεδομένες τεχνικές διαμόρφωσης του ηχητικού σήματος,
συγκεκριμένα η Διαμόρφωση Πλάτους (Amplitude Modulation - AM), η Διαμόρφωση Δακτυλίου (Ring Modulation),
η Διαμόρφωση Συχνότητας (Frequency Modulation - FM), και οι Περιβάλλουσες (Envelopes).
Έπειτα από μια ιστορική αναδρομή στην εξέλιξή τους, αναλύονται οι βασικές αρχές λειτουργίας τους
και περιγράφεται η ανάπτυξη των αντίστοιχων επεξεργαστικών εργαλείων.

** Θεωρία
AM, FM

** Pure Data
εργαλεία AM FM
Άσκηση: ενσωμάτωση στο όργανο

** SuperCollider


* Κεφάλαιο 12 - Προηγμένες Τεχνικές Σύνθεσης

Στο δωδέκατο κεφάλαιο αναλύονται προηγμένες τεχνικές ηχητικής σύνθεσης και
υλοποιούνται τα αντίστοιχα εργαλεία στα δύο προγραμματιστικά περιβάλλοντα.
Συγκεκριμένα, το ενδιαφέρον εστιάζεται στην Κοκκώδη Σύνθεση (Granular Synthesis),
στη Σύνθεση Μέσω Πινάκων (Wavetable Synthesis),
και στον Διακριτό Μετασχηματισμό Fourier (Fast Fourier Transform).

** Θεωρία
granular, wavetable, FFT

** Pure Data
granular, wavetable, waveshaping?
Άσκηση: ενσωμάτωση στο instrument

** SuperCollider


* Κεφάλαιο 11 - Τεχνικές Ανάδρασης

Στο ενδέκατο κεφάλαιο αναλύονται τεχνικές επεξεργασίας ηχητικού σήματος βασισμένες
στην ανάδραση που δημιουργεί η μεταβαλλόμενη χρονική του καθυστέρηση και ανατροφοδότηση.
Συγκεκριμένα, επεξηγούνται και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα
οι τεχνικές επεξεργασίας delay, echo, flanger, και reverb.

** Θεωρία
καθυστέρηση και ανατροφοδότηση, FIR και IIR φίλτρα

** Pure Data
αντικείμενα καθυστέρησης
Άσκηση: ενσωμάτωση στο όργανο

** SuperCollider


* Κεφάλαιο 13 - Σχεδιασμός Περιβάλλοντος Διεπαφής

Στο δέκατο τρίτο κεφάλαιο εξετάζονται θέματα σχεδιασμού του περιβάλλοντος διεπαφής
ως προς τη χρηστικότητα και φιλικότητά του προς τον τελικό χρήστη.
Εξετάζονται οι δυνατότητες κάθε γλώσσας για τη σε-πραγματικό-χρόνο εισαγωγή δεδομένων,
τη συνδεσιμότητα με εξωτερικούς ελεγκτές μέσω πρωτοκόλλου OSC, την οπτική οργάνωση
μέσω της χρήσης υποστηρικτικών γραφικών, και την ενσωμάτωση των υλοποιημένων εργαλείων
ως αυτόνομες εφαρμογές σε άλλες πλατφόρμες (VSTplugins).

** Θεωρία
GUI

** Pure Data
OSC, abstractions, plugins
Άσκηση: ενσωμάτωση σε όργανο

** SuperCollider





* Κεφάλαιο 14 - Αυτοσχεδιασμός και Αυτόματα

Στο δέκατο τέταρτο κεφάλαιο εξετάζονται θέματα υποβοήθησης της μουσικής εκτέλεσης
μέσω του ηλεκτρονικού υπολογιστή.
Αναφέρονται τεχνικές καταγραφής, ανάλυσης και μίμηση της εκτέλεσης,
καθώς και αυτοματοποιημενης αλγοριθμικής οργάνωσης.

** Θεωρία
 generative music, AI

** Pure Data
Άσκηση: ενσωμάτωση σε όργανο

** SuperCollider





* Κεφάλαιο 0 - Οπτική Αναπαράσταση του Ήχου

Σημαντική παράμετρος της μετάβασης σε προηγμένες τεχνικές ηχητικής σύνθεσης είναι
να αποκτήσει ο διδασκόμενος τα απαραίτητα εργαλεία επίβλεψης των ηχητικών χαρακτηριστικών,
ώστε να κατανοήσει καλύτερα τις διαδικασίες της μεταμόρφωσής του.
Ως εκ τούτου, στο ένατο κεφάλαιο παρουσιάζονται οι δυνατότητες των δύο λογισμικών
ως προς τη δυνατότητα οπτικής απεικόνισης και επίβλεψης του ήχου.
Τα εργαλεία απεικόνισης που αναλύονται αφορούν τόσο στη δυναμική της έντασης, όσο και στο συχνοτικό φάσμα του ήχου.

*** Θεωρία

*** Pure Data

*** SuperCollider
