* ΤΙΤΛΟΣ:

Εισαγωγή στο Μουσικό Προγραμματισμό

* ΥΠΟΤΙΤΛΟΣ:

Μουσική σύνθεση και ηχητική επεξεργασία στα ελεύθερα λογισμικά PureData και SuperCollider 

==========

* ΚΕΦΑΛΑΙΑ (συνοπτικά)

01. Εισαγωγή στα Περιβάλλοντα Μουσικού Προγραμματισμού
02. Πρώτα Βήματα 
03. Βασικά Στοιχεία και Δόμηση Μουσικών Προγραμμάτων
04. Ντετερμινισμός και Τυχαιοκρατία στη Μουσική Εκτέλεση
05. Αρχές Σύνθεσης και Επεξεργασίας Ήχου
06. Προσθετική και Αφαιρετική Σύνθεση
07. Μουσική Δόμηση του Ήχου
08. Το Ηχητικό Δείγμα
09. Οπτική Αναπαράσταση του Ήχου
10. Τεχνικές Διαμόρφωσης Σήματος
11. Τεχνικές Ανάδρασης
12. Προηγμένες Τεχνικές Σύνθεσης
13. Σχεδιασμός Περιβάλλοντος Διεπαφής

==========

* ΚΕΦΑΛΑΙΑ (αναλυτικά)

------------------

* Εισαγωγή στα Περιβάλλοντα Μουσικού Προγραμματισμού

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο πρώτο κεφάλαιο πραγματοποιείται μια ιστορική αναδρομή στη δημιουργία και εξέλιξη των γλωσσών μουσικού προγραμματισμού, τόσο στο σύνολό τους, όσο και ειδικότερα ως προς τα δύο ελεύθερα λογισμικά που αποτελούν το αντικείμενο του συγγράμματος. Παράλληλα, αναλύονται οι κοινωνικοί, πολιτικοί, και τεχνολογικοί παράγοντες που έπαιξαν καθοριστικό ρόλο στην ανάπτυξη και διάδοση των εν λόγω δημιουργικών εργαλείων στα πεδία της έρευνας και της βιομηχανία από τις πρώτες απόπειρες μουσικής σύνθεσης μέσω υπολογιστή μέχρι τον σύγχρονο εκδημοκρατισμό των τεχνολογικών μέσων για ηχητική σύνθεση και επεξεργασία. 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν διαγράψει μακρά πορεία στον τομέα της ηχητικής και μουσικής σύνθεσης σε εφαρμοσμένα πεδία, όπως οι διαδραστικές εγκαταστάσεις, οι θεατρικές παραστάσεις, και οι κινηματογραφικές παραγωγές, αξιοποιώντας ποικίλα λογισμικά και τεχνοτροπίες, ενώ τα έργα τους έχουν παρουσιαστεί σε συνέδρια, φεστιβάλ, και εκθέσεις στην Ελλάδα και το εξωτερικό. Σε ερευνητικό επίπεδο, ο Δρ. Ζάννος κατέχει Διδακτορικό σε Μουσικολογία από το Πανεπιστήμιο του Αμβούργου με ειδίκευση Ελληνική και Τουρκική Μουσική Θεωρία, και διδακτορικό από το Πανεπιστήμιο του Τόκιο σε Μηχανική Υπολογιστών με ειδίκευση στις γλώσσες προγραμματισμού για μουσική.  Επίσης, ο Δρ. Ζάννος έχει μακρόχρονη εμπειρία στον μουσικό προγραμματισμό με συμμετοχή σε ευρωπαϊκό έργο ώς διευθυντής του Τμήματος Μουσικής Τεχνολογίας και Τεκμηρίωσης του Ομοσπονδιακού Ινστιτούτου Μουσικής Έρευνας της Γερμανίας (SIM-PK), καθως και μετέπειτα ως διευθυντής έρευνας στο Κέντρο Έρευνας Δημιουργικών Τεχνών και Τεχνολογιών (CREATE) του Πανεπιστημίου της Καλιφόρνιας στην Σάντα Μπάρμπαρα. Τέλος έχει παρουσιάσει πολυάριθμα μουσικά έργα με ζωντανό προγραμματισμό σε ελληνικά και διεθνή συμπόσια και σε πλαίσιο ερευνητικών ευρωπαϊκών έργων. Διδάσκει Μουσικό Προγραμματισμό στο Τμήμα Τεχνών Ήχου και Εικόνας από το 2004, και έχει επίσης διδάξει το αντικείμενο αυτό τόσο στα παραπάνω αναφερθέντα ινστιτούτα όσο και σε διεθνή σεμινάρια σε πλαίσιο Ευρωπαϊκών Έργων και άλλων πρωτοβουλιών. Ο Δρ. Ροβίθης κατέχει διδακτορικό τίτλο στην Ηλεκτρονική Μουσική Σύνθεση και μεταπτυχιακό τίτλο στην Μουσική Σύνθεση. Σε διδακτικό επίπεδο, οι συγγραφείς έχουν διδάξει προπτυχιακά και μεταπτυχιακά μαθήματα που άπτονται απόλυτα του αντικειμένου του παρόντος συγγράμματος. Συγκεκριμένα στο παρόν κεφάλαιο αντιστοιχεί το μάθημα της Τεχνολογίας Ήχου. Απόσταγμα αυτών των μαθημάτων, οι διαλέξεις και εργαστηριακές σημειώσεις θα αξιοποιηθούν σε μεγάλο μέρος για τη συγγραφή του παρόντος συγγράμματος.   

 ------------------

* Πρώτα Βήματα

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο δεύτερο κεφάλαιο περιγράφονται τα γενικά χαρακτηριστικά των δύο προγραμματιστικών περιβαλλόντων, με έμφαση στα βασικά δομικά στοιχεία κάθε γλώσσας και τους τρόπους, με τους οποίους αυτά αλληλεπιδρούν. Το παρόν κεφάλαιο μαζί με τα δύο επόμενα ουσιαστικά πραγματεύονται την αρχιτεκτονική, τις αρχές λειτουργίας και το συντακτικό των λογισμικών. Μέσω σχετικών παραδειγμάτων επιδεικνύεται η ροή επεξεργασίας της πληροφορίας και αναλύονται οι ομοιότητες και διαφορές μεταξύ των δύο συστημάτων. 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Η επάρκεια των συγγραφέων ως προς τη δόμηση της παραδοτέας ύλης σε ενότητες αύξουσας πολυπλοκότητας, οι οποίες καθοδηγούν τον διδασκόμενο από το απλό προς το σύνθετο και δημιουργούν σε κάθε βήμα τις κατάλληλες συνθήκες για τη βέλτιστη κατανόηση του αντικειμένου, αποδεικνύεται από το ερευνητικό και διδακτικό τους έργο. Συγκεκριμένα, ο Δρ. Ζάννος έχει συγγράψει κεφάλαια και εργαστηριακές σημειώσεις για τη συστηματική εκμάθηση του SuperCollider, και ο Δρ. Ροβίθης έχει αντίστοιχα συγγράψει εργαστηριακές σημειώσεις για τη συστηματική εκμάθηση του Pure Data, υλικό που αποτελεί τον βασικό κορμό για τη συγγραφή του παρόντος συγγράμματος. 

 ------------------

* Βασικά Στοιχεία και Δόμηση Μουσικών Προγραμμάτων

ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

Στο τρίτο κεφάλαιο περιγράφονται τα βασικά επιμέρους στοιχεία κάθε γλώσσας, και περιγράφονται οι αρχές με τις οποίες συνδυάζονται για την δημιουργία μουσικών προγραμμάτων. Επίσης εισάγονται οι αρχές επεξεργασίας ψηφιακού σήματος και του προγραμματισμού, όπως σήμα, buffer, γεννήτρια, είσοδος, έξοδος, δίαυλος, μεταβλητή, συνάρτηση κ.α. Στόχος είναι να γίνει κατανοητό μέσω παραδειγμάτων πως ο συνδυασμός των στοιχείων αυτών μπορεί να οδηγήσει σε ένα μουσικό ή άλλο ηχητικό αποτέλεσμα. 

ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

Σχετικά με τα βασικά στοιχεία του Μουσικού Προγραμματισμού, ο Δρ. Ζάννος έχει συγγράψει το κεντρικό κεφάλαιο για το θέμα αυτό με τίτλο “Programming in SuperCollider” στο de facto κύριο σύγγραμμα για Μουσικό Προγραμματισμό με SuperCollider, (The SuperCollider Book, MIT Press, 2011).  Επίσης έχει συνεισφέρει στο ίδιο βιβλίο ως παράρτημα επισκόπηση του συντακτικού του SuperCollider.  O Δρ. Ροβίθης έχει συγγράψει σημειώσεις για τις προγραμματιστικές αρχές του Pure Data και έχει συνεργαστεί με τον Δρ. Ζάννο και με φοιτήτρια του Τμήματος Τεχνών Ήχου και Εικόνας σε πλαίσιο ατομικής εργασίας για την συγγραφή συγκριτικής μελέτης ανάμεσα σε Pure Data και SuperCollider. Τα παραπάνω εγγυώνται το απαραίτητο θεωρητικό και τεχνικό υπόβαθρο για τη ενδελεχή συγγραφή του παρόντος κεφαλαίου. Συμπληρωματικά προς όλα τα προηγούμενα, ο Δρ. Ροβίθης έχει διατυπώσει μια μεθοδολογική προσέγγιση για την ανάπτυξη διαδραστικού λογισμικού, καθώς και συγγράψει εργαστηριακές σημειώσεις δομημένες για τη συστηματική εκμάθηση περαιτέρω προγραμματιστικών περιβαλλόντων, όπως το GNU Octave. 

------------------

* Ντετερμινισμός και Τυχαιοκρατία στη Μουσική Εκτέλεση

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο τέταρτο κεφάλαιο αναλύονται αφενός η φιλοσοφία διαφορετικών μοντέλων παραγωγής και οργάνωσης των δεδομένων και αφετέρου η πραγμάτωσή τους στα δύο προγραμματιστικά περιβάλλοντα. Συγκεκριμένα, τα μοντέλα αυτά περιλαμβάνουν ντετερμινιστικές, πιθανοκρατικές, και τυχαιοκρατικές προγραμματιστικές δομές. Το θεωρητικό μέρος του κεφαλαίου εστιάζει στην ιστορική εξέλιξη τέτοιων δομών, καθώς και στην εφαρμογή τους για τη δημιουργία έργων ψηφιακής τέχνης, ενώ το πρακτικό μέρος αναλύει τη χρήση λογικών ελεγκτών για τον συσχετισμό των επιμέρους στοιχείων και τη συναρμολόγηση συστημάτων σύμφωνα με τις αρχές κάθε οργάνωσης.

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν ασχοληθεί εκτενώς με διαδραστικά συστήματα που επιτρέπουν αυξημένη -ανάλογα με την περίσταση- αλληλεπίδραση με το τελικό αποτέλεσμα, και ως εκ τούτου, είναι πλήρως εξοικειωμένοι με την εφαρμογή διαφορετικών μοντέλων τυχαιότητας ως προς την παραγωγή και διαχείριση του υλικού. O Δρ. Ζάννος έχει συγγράψει άρθρο σε διεθνές επιστημονικό περιοδικό σχετικά με την δημιουργία και ερμηνεία καλλιτεχνικών δομών από ντετερμινιστικούς αλγορίθμους με απρόβλεπτα χαρακτηριστικά. Επιπλέον, η διδακτική εμπειρία τους στο αντικείμενο της Αλγοριθμικής Σύνθεσης και Δόμησης του Ήχου και οι εξ αυτής εκπορευόμενες σημειώσεις παρέχουν το απαραίτητο υλικό για τη συγγραφή του παρόντος κεφαλαίου.  


.

* Αρχές Σύνθεσης και Επεξεργασίας Ήχου

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο πέμπτο κεφάλαιο περιγράφονται και στα δύο προγραμματιστικά περιβάλλοντα οι βασικές αρχές ηχητικής σύνθεσης και επεξεργασίας. Συγκεκριμένα αναλύονται οι εσωτερικές διαδικασίες παραγωγής ήχου μέσω ηλεκτρονικού υπολογιστή από το πιο απλό είδος ταλάντωσης, δηλαδή της ημιτονοειδούς ταλάντωσης, και πιο σύνθετων κυματομορφών, όπως της πριονωτής, της τριγωνικής και της τετράγωνης κυματομορφής, έως την παραγωγή θορύβου ως πρωτογενούς ηχητικού υλικού. Αναφέρονται οι ηχητικές ιδιότητες της θεμελιώδους συχνότητας και των αρμονικών, καθώς και οι ακουστικές διαστάσεις των διαφορετικών ειδών θορύβου βάσει του συχνοτικού φάσματος. Τέλος, ο αναγνώστης καθοδηγείται προς τη δημιουργία μιας γεννήτριας ταλαντωτών. Το παρόν κεφάλαιο μαζί με τα τρία επόμενα εστιάζει στις ηχητικές πηγές και σε απλούς τρόπους επεξεργασίας τους.   

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Η διδακτική εμπειρία των συγγραφέων στο γνωστικό αντικείμενο της Ψηφιακής Επεξεργασίας Ήχου και ειδικότερα ως προς θέματα που άπτονται της δημιουργίας συνθετητών μέσω γεννητριών ταλαντωτών, αποτελεί την επαρκή βάση για τη συγγραφή του παρόντος κεφαλαίου. Το εισαγωγικό σύγγραμμα του Δρ. Ζάννου “Step-by-Step Guide to Supercollider” περιέχει εκτεταμένες εισαγωγικές εξηγήσεις για το θέμα αυτό, συνοδευόμενες από παραδείγματα και διαγράμματα Επιπλέον, ο Δρ. Ροβίθης έχει ασχοληθεί στο παρελθόν εκτεταμένα με τη διερεύνηση της φύσης του θορύβου και τη δημιουργία παιγνιακών συστημάτων με στόχο την ευαισθητοποίηση σχετικά με τον αντίκτυπο του θορύβου στην ακουστική οικολογία, ενασχόληση που οδήγησε σε δημοσίευση στην επιστημονική κοινότητα της κατηγοριοποίησης των ηχητικών συμβάντων θορύβου βάσει των ακουστικών και λειτουργικών χαρακτηριστικών τους. 

* Προσθετική και Αφαιρετική Σύνθεση

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο έκτο κεφάλαιο πραγματοποιείται επίδειξη των τεχνικών της προσθετικής και αφαιρετικής σύνθεσης. Αναλύονται στα δύο προγραμματιστικά περιβάλλοντα οι διαδικασίες συχνοτικής επεξεργασίας τόσο μέσω της πρόσθεσης ταλαντωτών, όσο και μέσω φίλτρων συχνοτικής αποσιώπησης και ενίσχυσης. Τέλος, ο αναγνώστης καθοδηγείται προς την υλοποίηση γεννήτριας προσθετικής επεξεργασίας πολλαπλών ταλαντωτών, και παραγωγής θορύβου με δυνατότητα συχνοτικής επεξεργασίας μέσω εργαλείου παραμετροποιημένης ισοστάθμισης. 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Η διδακτική εμπειρία των συγγραφέων στο γνωστικό αντικείμενο της Ψηφιακής Επεξεργασίας Ήχου και ειδικότερα ως προς θέματα που άπτονται των τεχνικών προσθετικής και αφαιρετικής σύνθεσης, αποτελεί την επαρκή βάση για τη συγγραφή του παρόντος κεφαλαίου. Παραδείγματα βρίσκονται στο σύγγραμμα του Δρ. Ζάννος “A Step-by-Step Guide to SuperCollider”. 

* Μουσική Δόμηση του Ήχου

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο έβδομο κεφάλαιο αναλύεται η διαχείριση midi πληροφοριών, από τη μετατροπή του μεγέθους της συχνότητας σε midi τιμή, μέχρι τη δημιουργία και στις δύο γλώσσες προγραμματισμού μιας γεννήτριας ηχητικών συμβάντων με δυνατότητες ενεργοποίησης των midi ήχων του υπολογιστή και οργάνωσής τους σε ακολουθίες κατά τα πρότυπα διαφορετικών μουσικών κλιμάκων. Επεξηγούνται οι προγραμματιστικές έννοιες των μοτίβων (patterns), επαναλαμβανόμενων διεργασιών (routines and tasks), και των πληροφοριακών ροών (streams), ως προς τη λειτουργία τους για τη διαχείριση ηχητικών δεδομένων. Επιπλέον, περιγράφονται οι έννοιες της οκτάβας και της μουσικής κλίμακας, και αναφέρεται η γέννηση και ο σημαντικός αντίκτυπος της midi τεχνολογίας στη μουσική βιομηχανία. Τέλος, συνδυάζονται προηγούμενες γνώσεις σχετικές με τα μοντέλα πιθανοκρατικής διαχείρισης της πληροφορίας για τη δημιουργία εργαλείου για μουσικό αυτοσχεδιασμό υποβοηθούμενο από τον υπολογιστή.  

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Η επαγγελματική ενασχόληση του Δρ. Ροβίθη με το αντικείμενο της εφαρμοσμένης μουσικής σύνθεσης για θεατρικές και κινηματογραφικές παραγωγές, καθώς και οι πολύχρονες σπουδές του στη μουσική σε θεωρητικό και εκτελεστικό επίπεδο, διασφαλίζουν τις συνθήκες για τη συγγραφή του παρόντος κεφαλαίου, το οποίο εστιάζει στη μουσική προτυποποίηση των υπολογιστικών δεδομένων. Επιπλέον, η εμπειρία του Δρ. Ζάννου στη διδασκαλία του αντικειμένου της Αλγοριθμικής Σύνθεσης και Δόμησης Ήχου παρέχει την απαραίτητη βάση για το συνδυασμό της μέχρι στιγμής δεδιδαγμένης ύλης προς τη δημιουργία ενός σύνθετου εργαλείου.   Ο Δρ. Ζάννος έχει αναρτήσει εκτενή παραδείγματα στο διαδίκτυο σε μορφή αποθετηρίων στο github, που είναι σε χρήση στην τρέχουσα διδασκαλία σχετικών μαθημάτων. 

* Το Ηχητικό Δείγμα

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο όγδοο κεφάλαιο το ενδιαφέρον εστιάζεται σε τεχνικές ηχητικής σύνθεσης βασισμένες στην εισαγωγή και επεξεργασία ηχητικού δείγματος. Παρουσιάζεται η ιστορική εξέλιξη του sampling από τις πρώτες μεθοδικές προσεγγίσεις μέχρι τη σύγχρονη τεχνολογία αιχμής, και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα αντίστοιχα εργαλεία εισαγωγής, αναπαραγωγής, και τεμαχισμού δείγματος, και ανακατανομής τμημάτων. Έπειτα αναλύονται και υλοποιούνται τεχνικές επεξεργασίας πλάτους σήματος, όπως η κανονικοποίηση (normalization), η συμπίεση (compression) και η διόγκωση (expansion).

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν πολυετή εμπειρία στη διδασκαλία μαθημάτων που άπτονται του γνωστικού αντικειμένου της Ψηφιακής Επεξεργασίας Ήχου και της Αλγοριθμικής Σύνθεσης και Δόμησης Ήχου, και ως εκ τούτου περιλαμβάνουν στην ύλη τους τεχνικές εισαγωγής και επεξεργασίας ηχητικών δειγμάτων.  Σαν μέρος της ύλης προορίζονται παραδείγματα από έργα των διδασκόντων που έχουν κάνει εκτενή χρήση αυτών των τεχνικών. Παραδείγματα κώδικα βρίσκονται σε σχετικά αποθετήρια στο github όπως https://github.com/iani/sc-hacks.   

* Οπτική Αναπαράσταση του Ήχου

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Σημαντική παράμετρος της μετάβασης σε προηγμένες τεχνικές ηχητικής σύνθεσης είναι να αποκτήσει ο διδασκόμενος τα απαραίτητα εργαλεία επίβλεψης των ηχητικών χαρακτηριστικών, ώστε να κατανοήσει καλύτερα τις διαδικασίες της μεταμόρφωσής του. Ως εκ τούτου, στο ένατο κεφάλαιο παρουσιάζονται οι δυνατότητες των δύο λογισμικών ως προς τη δυνατότητα οπτικής απεικόνισης και επίβλεψης του ήχου. Τα εργαλεία απεικόνισης που αναλύονται αφορούν τόσο στη δυναμική της έντασης, όσο και στο συχνοτικό φάσμα του ήχου.


**  ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:
 Η εμπειρία των συγγραφέων στη διδασκαλία μαθημάτων σχετιζόμενων με τα αντικείμενα της Ψηφιακής Επεξεργασίας Ήχου και της Τεχνολογίας Ήχου, καθώς και η εξοικείωσή τους με ποικίλα λογισμικά και τις δυνατότητες ηχητικής απεικόνισης και επίβλεψης που περιλαμβάνουν, παρέχουν την απαραίτητη γνωστική επάρκεια για τη συγγραφή του παρόντος κεφαλαίου.  

* Τεχνικές Διαμόρφωσης Σήματος

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο δέκατο κεφάλαιο παρουσιάζονται ευρέως διαδεδομένες τεχνικές διαμόρφωσης του ηχητικού σήματος, συγκεκριμένα η Διαμόρφωση Πλάτους (Amplitude Modulation - AM), η Διαμόρφωση Δακτυλίου (Ring Modulation), η Διαμόρφωση Συχνότητας (Frequency Modulation - FM), και οι Περιβάλλουσες (Envelopes). Έπειτα από μια ιστορική αναδρομή στην εξέλιξή τους, αναλύονται οι βασικές αρχές λειτουργίας τους και περιγράφεται η ανάπτυξη των αντίστοιχων επεξεργαστικών εργαλείων.

 ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν πολυετή εμπειρία στη διδασκαλία μαθημάτων που άπτονται του γνωστικού αντικειμένου της Ψηφιακής Επεξεργασίας Ήχου και περιλαμβάνουν στην ύλη τους τεχνικές διαμόρφωσης ηχητικών σημάτων. Επιπλέον, έχουν αξιοποιήσει επανειλημμένως τις συγκεκριμένες τεχνικές για τη δημιουργία διαδραστικών καλλιτεχνικών έργων βασισμένων σε αρχές ηχητικής αναπαράστασης δεδομένων.

 ------------------

* Τεχνικές Ανάδρασης    (delay echo, flanger, reverb)

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο ενδέκατο κεφάλαιο αναλύονται τεχνικές επεξεργασίας ηχητικού σήματος βασισμένες στην ανάδραση που δημιουργεί η μεταβαλλόμενη χρονική του καθυστέρηση και ανατροφοδότηση. Συγκεκριμένα, επεξηγούνται και υλοποιούνται στα δύο προγραμματιστικά περιβάλλοντα οι τεχνικές επεξεργασίας delay, echo, flanger, και reverb. 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν πολυετή εμπειρία τόσο στη διδασκαλία μαθημάτων που άπτονται του γνωστικού αντικειμένου της Ψηφιακής Επεξεργασίας Ήχου, όσο και στη μουσική παραγωγή, πεδία που αξιοποιούν συστηματικά τις συγκεκριμένες επεξεργαστικές διαδικασίες. Και για αυτό το κεφάλαιο βρίσκονται ήδη παραδείγματα από έργα και ερευνητικές εργασίες σε σχετικά αποθετήρια όπως https://github.com/iani/sc-hacks

* Προηγμένες Τεχνικές Σύνθεσης

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο δωδέκατο κεφάλαιο αναλύονται προηγμένες τεχνικές ηχητικής σύνθεσης και υλοποιούνται τα αντίστοιχα εργαλεία στα δύο προγραμματιστικά περιβάλλοντα. Συγκεκριμένα, το ενδιαφέρον εστιάζεται στην Κοκκώδη Σύνθεση (Granular Synthesis), στη Σύνθεση Μέσω Πινάκων (Wavetable Synthesis), και στον Διακριτό Μετασχηματισμό Fourier (Fast Fourier Transform). 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Οι συγγραφείς έχουν πολυετή εμπειρία τόσο στη διδασκαλία μαθημάτων που άπτονται του γνωστικού αντικειμένου της Ψηφιακής Επεξεργασίας Ήχου, όσο και στη μουσική παραγωγή, πεδία που αξιοποιούν συστηματικά τις εν λόγω επεξεργαστικές διαδικασίες. Και για αυτό το κεφάλαιο βρίσκονται ήδη παραδείγματα από έργα και ερευνητικές εργασίες σε σχετικά αποθετήρια όπως https://github.com/iani/sc-hacks


* Σχεδιασμός Περιβάλλοντος Γραφικής Διεπαφής

** ΣΥΝΤΟΜΗ ΠΕΡΙΓΡΑΦΗ:

 Στο δέκατο τρίτο κεφάλαιο εξετάζονται θέματα σχεδιασμού του περιβάλλοντος διεπαφής ως προς τη χρηστικότητα και φιλικότητά του προς τον τελικό χρήστη. Εξετάζονται οι δυνατότητες κάθε γλώσσας για τη σε-πραγματικό-χρόνο εισαγωγή δεδομένων, τη συνδεσιμότητα με εξωτερικούς ελεγκτές μέσω πρωτοκόλλου OSC, την οπτική οργάνωση μέσω της χρήσης υποστηρικτικών γραφικών, και την ενσωμάτωση των υλοποιημένων εργαλείων ως αυτόνομες εφαρμογές σε άλλες πλατφόρμες (VST/plugins). 

** ΑΝΑΦΟΡΑ ΣΕ ΣΧΕΤΙΚΟ ΕΡΓΟ – ΤΕΚΜΗΡΙΩΣΗ:

 Ο Δρ. Ροβίθης έχει εκτεταμένα ασχοληθεί με θέματα σχεδιασμού περιβαλλόντων διεπαφής για ηχητική αλληλεπίδραση, καθώς και με την αξιοποίησή τους στην  εκπαίδευση και τη δημιουργία σε συνδυασμό με τεχνολογίες αιχμής. Ερευνητικές μελέτες που έχει πραγματοποιήσει σχετικά με τα χαρακτηριστικά της ηχητικής αλληλεπίδρασης στο πλαίσιο ηλεκτρονικών ηχητικών και ακουστικώς επαυξημένων διαδραστικών περιβαλλόντων (Audio Games / Augmented Reality Audio Games) έχουν δημοσιευτεί σε διεθνή επιστημονικά περιοδικά πλήρους κρίσης. Επιπλέον, η προσέγγιση των μαθημάτων που διδάσκουν οι συγγραφείς είναι εργο-κεντρική, με στόχο την εφαρμογή της γνώσης των φοιτητών για την υλοποίηση ενός συλλογικού τελικού έργου, το οποίο προβλέπει  διαβαθμίσεις ελευθερίας ως προς τη συμμετοχή του κοινού και την επικοινωνία του με το τελικό αποτέλεσμα. Ως εκ τούτου, οι συγγραφείς είναι πλήρως εξοικειωμένοι με τον σχεδιασμό διαδραστικών λογισμικών εφαρμογών σε εκπαιδευτικό πλαίσιο και τα ζητήματα διεπαφής και χρηστικότητας που αφορούν σε τέτοια εγχειρήματα. Ενδεικτικό παράδειγμα αυτής της εργο-κεντρικής προσέγγισης του Δρ. Ροβίθη έχει επικοινωνηθεί στην ακαδημαϊκή κοινότητα μέσω ανακοίνωσης σε επιστημονικό συνέδριο. Ο Δρ. Ζάννος έχει επίσης δημοσιεύσει άρθρα σχετικά με αυτό το θέμα, καθώς και εκδώσει εκτενή βιβλιοθήκη για γραφικό περιβάλλον διεπαφής στο SuperCollider η οποία περιγράφεται σε ανακοινώσεις συνεδρίων. 

